### ISSUE TITLE
ZFS inter-process locks should track the subprocess pid

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#162]
Upon reviewing the global locking, it appears that the PID being locked on is the parent PID.

Instead, it should probably lock on the child PID I.E. the subprocess calls to `zpool import` etc...

That way, we can ensure that the child PID has exited when we perform cleanup, as that is the PID we want to make sure has finished. 

When we exit the agent, and delete locks; we should also ensure the child process is no longer running.

**Comment by tanabarr** [comment]
closed given we won't be using the locking mechanism for much longer
