### ISSUE TITLE
rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#173]
Our syslog's `/var/log/messages` files are getting riddled with tons of:

```
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
Jul 25 21:29:11 lotus-52vm18.lotus.hpdd.lab.intel.com rsyslogd: action 'action 8' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
```

messages.

**Comment by brianjmurrell** [comment]
This issue is exploding log file sizes, in one case (the only one I have looked at so far) by 10x from 3M to 30M.

**Comment by brianjmurrell** [comment]
In another case, from 11MB to just over 100MB.

The log spam on production systems aside, this makes the _messages_ files in _chroma-diagnostics_ files 10x as big as they should/need to be.

**Comment by brianjmurrell** [comment]
I believe this is caused when the IML log ingester (`*.* @@127.0.0.1:515;RSYSLOG_ForwardFormat`) is not running and so rsyslog is getting TCP RSTs when trying to connect to it.

We can tell _rsyslog_ not to annoy us about such events.

**Comment by jgrund** [comment]
Makes sense.

Newer versions of rsyslog should also tell you the error before resuming.

**Comment by brianjmurrell** [comment]
0.8.29 adds some verbosity around suspend/resume events.  It seems there have also been bugs around not emitting suspend events since each resume should have a corresponding suspend event.

But now that I give this more thought, the problem might actually be different.

Once the action has been suspended, due to getting at TCP RST I would expect to not get any more errors until the resume, after which I would expect to only get a single suspend, until another resume.

But what I noticed in my debugging is that our ingester is actually closing down the TCP session after each log message send.  It might actually be this which is causing such a high volume of these suspenend/resume events (which we only get the resume message for).

If this is the case, the proper fix is to our log ingester, not suppressing these messages.
