### ISSUE TITLE
Create Contributor Docs

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#183]
Create a set of contributor docs that tell contributors unfamiliar about IML, how to contribute to the project, and it's overall architecture. At a minimum we should include:

- [x] High level overview of repos and how they fit together
- [x] How to contribute a patch to both a small repo and the intel-manager-for-lustre repo.
- [x] High level architecture of IML
- [x] Review docs for correct content
- [x] Review docs for grammar 
- [x] Make Corrections from Reviews 
- [x] Add contributor docs to IML Help Docs
- [x] Add corrections to make docs consistent with Help Docs

**Comment by petertix** [comment]
Moved Docs to:
https://github.com/intel-hpdd/Online-Help/pull/21
