### ISSUE TITLE
Read/Write Bandwidth Chart shows "No Data Available"  in Server Dashboard 

### ISSUE THREAD

**Issue by jiamliang** [intel-hpdd/intel-manager-for-lustre#198]
### Description 
I have installed lustre 2.9.0 on bare metal.
MGS/MDS :  0c-c4-7a-15-e1-9c (hostname)   mgt:  /dev/sdb2  mdt: /dev/sdb1
OSS0: 00-25-90-c0-f7-c8   ost0:  /dev/sdb
OSS1: 00-25-90-c0-f7-88   ost1:  /dev/sdb

IML 4.0.0 Preview 2  installed on host: pxe-15-253

I have added 3 of the lustre servers into IML, detect lustre file system and everything looks good.
Read/Write Bandwidth Chart shows "No Data Available" In Server Dashboard, 

![image](https://user-images.githubusercontent.com/1405049/29113156-df04497c-7d22-11e7-98e5-c86a671c8919.png)

### Repro

1. add repo as shown in https://github.com/intel-hpdd/intel-manager-for-lustre/wiki/Installing-IML-Preview1-on-a-cluster
2. download and install IML  4.0.0 Preview 2  with command:  ./install --no-repo-check  --no-dbspace-check
3. login IML  
4. add lustre servers to IML in Configuration->Servers  as "Monitored Storage Server"
5. click "Detect File Systems" and import lustre file system into "File Systems"

### Version
IML 4.0.0 Preview 2
CentOS 7.3.1611  3.10.0-514.2.2.el7.x86_64

Please help.
Thanks!

**Comment by brianjmurrell** [comment]
Can you reproduce this using Lustre 2.10?  That is the version that IML is currently targeting and being tested with the preview releases.

**Comment by jonhamidi** [comment]
Seems to be working in the latest lustre:

![screen shot 2017-08-09 at 4 48 50 pm](https://user-images.githubusercontent.com/27026480/29145927-a33d52c4-7d24-11e7-84e2-6ed79763284a.png)

**Comment by yhamidi** [comment]
It seems to be working in Lustre 2.10:

![screen shot 2017-08-09 at 4 48 50 pm](https://user-images.githubusercontent.com/27026630/29146180-8b3b8be0-7d25-11e7-958a-777639d9b511.png)

**Comment by yhamidi** [comment]
I was looking at the wrong server. The MDT server does have the bug:

![screen shot 2017-08-09 at 5 15 42 pm](https://user-images.githubusercontent.com/27026630/29146447-cea1efd6-7d26-11e7-8a72-8d4074929757.png)

**Comment by jiamliang** [comment]
In my case, every server has the same bug.

**Comment by jiamliang** [comment]
There is an Error Occurred when I click on the "Chart Icon" at the right side of  "File Systems -> lustre -> OSTs (MDTs/MGTs)-> lustre-XXX0000x"

![image](https://user-images.githubusercontent.com/1405049/29149558-7e54f0b0-7da7-11e7-9252-0df797cd71fc.png)

Message:

> [$interpolate:interr] Can't interpolate: configure/server/{{targetDashboard.target.active_host | extractApi}}
> Error: could not extract api id from undefined
> http://errors.angularjs.org/1.5.11/$interpolate/interr?p0=configure%2Fserver%2F%7B%7BtargetDashboard.target.active_host%20%7C%20extractApi%7D%7D&p1=Error%3A%20could%20not%20extract%20api%20id%20from%20undefined

Client Stack Trace:

> Error: [$interpolate:interr] Can't interpolate: configure/server/{{targetDashboard.target.active_host | extractApi}}
> Error: could not extract api id from undefined
> http://errors.angularjs.org/1.5.11/$interpolate/interr?p0=configure%2Fserver%2F%7B%7BtargetDashboard.target.active_host%20%7C%20extractApi%7D%7D&p1=Error%3A%20could%20not%20extract%20api%20id%20from%20undefined
>     at https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:374
>     at Function.ci.interr (https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:113844)
>     at l.exp (https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:53836)
>     at Object.pre (https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:39867)
>     at https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:5636
>     at Mt (https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:40610)
>     at p (https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:32827)
>     at a (https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:28666)
>     at https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:28197
>     at https://10.10.15.253/gui/main.99de3e4adcf92226aeb5.js:12:30967

**Comment by jiamliang** [comment]
@brianjmurrell Which IML version is being tested and works well for lustre 2.9.0 ？
Thanks a lot.

**Comment by jgrund** [comment]
Hi @jiamliang, there is currently no version of IML that is tested with Lustre 2.9. 

That said, we are looking at updating the way we interact with Lustre; which may open the door to supporting versions prior to 2.10.

Thanks for reporting that stacktrace btw, should have that fixed shortly.

**Comment by jiamliang** [comment]
@jgrund Thanks a lot.
