### ISSUE TITLE
Provisioner output file lists corosync ring1 interface incompatible with vbox provider

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#211]
The interface name populated in provisioner_output-vagrant-ssi.json is incorrect for vbox provider, under corosync_config section, ring1_iface parameter is "eth3" which is an invalid network Interface identifier on virtualbox provided VMs that we use.

Persistent network interface naming as on the Virtualbox VMs we use in our vagrant solution: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Understanding_the_Predictable_Network_Interface_Device_Names.html

This needs to be resolved in order to run SSI tests on Windows, hence this work is part of #201

**Comment by brianjmurrell** [comment]
This is really a difference between the Vagrant boxes that are being used for _libvirt_ and _vbox_.  The former is using the default box supplied by the CentOS project and so should likely be considered canonical and any box we build should mirror the default provided one as much as possible.  That box is using eth[0-9] naming.

**Comment by tanabarr** [comment]
@malk271 is looking at the "eno vs eth' issue, copying some of his comments here: 
 >> I started to have a look a the Vagrant providers today -- I'm either going to have to pick apart the loops and manage each unit individually, or start to live with a few compromises. The eno vs eth devices problem is down to the device driver and the driver emulation -- I'll try to take a look at that as well. The unfortunate thing about the Vagrant providers is the way in which VBox has been abstracted. It's both a function of the way that CentOS has created its official boxes, and Vagrant's own limitations. On possibility is to create includes based on the provider chosen, and split the functionality into separate files. I'm just concerned about duplicating code between the two.
