### ISSUE TITLE
Cannot install nodejs on Centos7

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#213]
The http-parser package has been moved to base and removed from epel repo. It is therefore unavailable until rhel/centos 7.4. 
The workaround for https://bugs.centos.org/view.php?id=13669&nbn=1 (installing nodejs 6 on Centos7,) is to manually install http-parser

```
rpm -ivh https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm && yum -y install nodejs
```

We could upload to COPR?

**Comment by brianjmurrell** [comment]
I have already [filed an issue](https://bugzilla.redhat.com/show_bug.cgi?id=1481470) with EPEL about this and also had already opened a [PR](https://github.com/intel-hpdd/manager-for-lustre-dependencies/pull/40) to build http-parser last night.

**Comment by brianjmurrell** [comment]
[Fixed](https://github.com/intel-hpdd/manager-for-lustre-dependencies/pull/40)
