### ISSUE TITLE
Failure to add server to empty configuration

### ISSUE THREAD

**Issue by drufu** [intel-hpdd/intel-manager-for-lustre#217]
### Description 
After a fresh installation of version 4.0.0.P2 and successful configuration of PostgreSQL, it's possible to log in but adding a server fails: after entering the name and clicking NEXT, the "status square" is green (the ssh connection works). Clicking on PROCEED produces the js error attached (u.default.find() is undefined).

### Repro
Fresh installation of CC7 (Minimal Setup), install IML4.0.0P2.
Firewall disabled
selinux disabled

### Version
What version of IML? 4.0.0.P2 
What Operating System? CC7 x64
What Operating System version? 7.3.1611 (Core), kernel 3.10.0-514.21.1.el7.x86_64

![add-server-js-error](https://user-images.githubusercontent.com/31067729/29362466-6aecf632-828c-11e7-9ca9-305c5bdca4ad.png)

[diagnostics_aidrefsrv01.cern.ch_20170727T094929.tar.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1228085/diagnostics_aidrefsrv01.cern.ch_20170727T094929.tar.zip)

**Comment by brianjmurrell** [comment]
> diagnostics_aidrefsrv01.cern.ch_20170727T094929.tar.zip

Just as an aside, you don't need to compress the `.tar.lzma` file with something like ZIP.  LZMA is a compression algorithm and trying to compress it with something like ZIP will likely result in a bigger file.  Not always, but often times.

**Comment by drufu** [comment]
Hello,
true, but GitHub doesn't like it !

![github-filetypes](https://user-images.githubusercontent.com/31067729/29362799-a1e2cc56-828d-11e7-94e5-d26152f3e1c5.png)

**Comment by brianjmurrell** [comment]
> GitHub doesn't like it !

Oh, I see.  Pity.  I've requested _lzma_ be added as a supported file type.

**Comment by jgrund** [comment]
Hi,

The issue here is the profiles were not added to the database. You can remedy this by running the `install` script from the tarball again (while keeping the existing install in place).

You may see an error regarding EPEL during the next install. if you do, run `install --no-repo-check`.

Once you do this, you should be able to continue adding servers.

**Comment by drufu** [comment]
Hello,
thanks for the hint. Indeed it helped, I could add the server but deploying the agent failed and now the whole IML installation is down, the logs mention socket errors .. so I suspect that after re-running the install all services try to start several times now and keep killing themselves. "chroma-config validate" reports services not running, but a different set of services every time you run the command. Plus the supervisor seems to be crashing now:
Aug 21 09:51:31 localhost python: detected unhandled Python exception in './manage.py'

[diagnostics_aidrefsrv05.cern.ch_20170821T100006.tar.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1238162/diagnostics_aidrefsrv05.cern.ch_20170821T100006.tar.zip)

**Comment by jgrund** [comment]
Hi @drufu, Please collect diagnostics from one of the storage nodes. 

In addition, did you add the necessary repos to the storage nodes before deploying the agent?

**Comment by drufu** [comment]
Hello,
OSS: rabbitmqctl does not exist. Only the yum repo definition file was put in place but no other modifications were done on the server. 
Please, what are the "necessary repos" you mention ?? No idea. There is no documentation or readme file of any kind, so we're totally flying blind here .. 
We already spent some time on it and with the provided yum repo a "yum install chroma-agent" (the only package provided through the IML server) fails because of missing dependencies, which seem to be the same as for installing the IML management server. So we put this repo in place in addition. But as we don't know what to install / command to run and in addition the IML management server seems to be broken now, we're a stuck here ..

**Comment by jgrund** [comment]
Sorry, should have been clearer; Your should run that command on your management node. Just wanted to confirm your rabbitmq was still in a nodedown state
as your last diagnostic report is showing.

**Comment by jgrund** [comment]
In terms of documentation, here is a page describing how to setup the preview 2 release on a cluster: https://github.com/intel-hpdd/intel-manager-for-lustre/wiki/Setup-IML-Preview-2-on-a-cluster. Please keep in mind that as this is a preview release, it is not intended for general production use, and the steps will change in the final release.

We also have online help for general IML documentation: https://intel-hpdd.github.io/Online-Help

**Comment by drufu** [comment]
Hello,
for the rabbitmqctl: all chroma processes etc are restarting constantly, every time you run chroma-validate there's another set of daemons missing. Starting from the beginning:

[root@aidrefsrv05 ~]# chroma-config validate
Checking service configuration...
Errors found:
  * Service chroma-supervisor is not running
  * Service nginx is not running

[root@aidrefsrv05 ~]# chroma-config start
Starting daemons
[root@aidrefsrv05 ~]# chroma-config validate
Checking service configuration...
Errors found:
  * Service lustre_audit is not running (status STARTING)
  * Service syslog is not running (status STARTING)
[root@aidrefsrv05 ~]# chroma-config validate
Checking service configuration...
Errors found:
  * Service http_agent is not running (status STARTING)
  * Service job_scheduler is not running (status STARTING)
[root@aidrefsrv05 ~]# chroma-config validate
Checking service configuration...
Errors found:
  * Service corosync is not running (status STARTING)
  * Service http_agent is not running (status STARTING)
  * Service syslog is not running (status STARTING)
[root@aidrefsrv05 ~]# chroma-config validate
Checking service configuration...
Errors found:
  * Service lustre_audit is not running (status STARTING)
  * Service stats is not running (status STARTING)
  * Service syslog is not running (status STARTING)

..


[root@aidrefsrv05 ~]#  rabbitmqctl list_queues -p chromavhost  
Listing queues ...
Error: unable to connect to node rabbit@aidrefsrv05: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@aidrefsrv05]

rabbit@aidrefsrv05:
  * connected to epmd (port 4369) on aidrefsrv05
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: hostname mismatch?
  * suggestion: is the cookie set correctly?

current node details:
- node name: rabbitmqctl2529@aidrefsrv05
- home dir: /var/lib/rabbitmq
- cookie hash: 9FaajDUllEBZD8GYHZohTw==

**Comment by drufu** [comment]
Hello,
the key was to have all repos from
https://copr-be.cloud.fedoraproject.org/results/managerforlustre/
available when running the install. 
I wiped out the PostgreSQL db and ran the install again.
Now everything works. 
Thanks,
