### ISSUE TITLE
Corosync config fails

### ISSUE THREAD

**Issue by drufu** [intel-hpdd/intel-manager-for-lustre#245]
### Description 
Corosync config fails on nodes with two TCP interfaces
Both network interfaces are up and all nodes can communicate on both networks. The Corosync setup fails to detect the corresponding interface.

### Repro
Add new MDS/OSS

### Version

What version of IML? 4.0.0.P2
What Operating System? CC7 x64
What Operating System version? 7.3.1611 (Core), kernel 3.10.0-514.21.1.el7.x86_64

![coro-0](https://user-images.githubusercontent.com/31067729/29749419-55f168c4-8b2b-11e7-9bf0-221cc0bbeba0.png)
![coro-1](https://user-images.githubusercontent.com/31067729/29749420-60dc21d4-8b2b-11e7-9b03-4ad6295f448d.png)
![coro-2](https://user-images.githubusercontent.com/31067729/29749421-6334dfe8-8b2b-11e7-8ac2-6042a866e466.png)

**Comment by brianjmurrell** [comment]
The _ring1_ interface needs to be **unconfigured** for IML to find and use it.  It also has to be physically cabled to the peer node in a "crossover" configuration.  For modern NICs this simply means running a standard cable between the nodes as the NICs will detected that and one of them will cross-over internally.

So on the interface you want to be used for the Corosync ring1 interface -- the one you have directly connected to the peer node -- you can run `ifconfig <interface> 0.0.0.0 up` to unconfigure it.  Once you have done that on both nodes of the pair, IML should be able configure the interface as the Corosync ring1 interface.

**Comment by drufu** [comment]
that worked .. even with a switch for the whole cluster ..  
Thanks.

**Comment by brianjmurrell** [comment]
> that worked .. even with a switch for the whole cluster ..

Not sure what that means exactly, but to be clear, you would not want to put your ring1 interface on the same switch as the main management interface (i.e. the one that the IML manager will contact the storage servers on) for your storage servers.

If you do that, your switch becomes a single point of failure for both Corosync communication channels, voiding the entire purpose of having two Corosync communication channels.

Additionally, IML has not been tested where the ring1 interface for multiple pairs of nodes are on the same media.  IML uses some special techniques on that ring1 network to auto-detect a usable address/port for Corosync and having multiple pairs on the same network might confuse those techniques.
