### ISSUE TITLE
chroma-agent-daemon not stopping gracefully

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#258]
While debugging #173 I observed repeatedly that when stopping the _chroma-agent-daemon_ with `systemctl stop chroma-agent`, the agent does not exit gracefully but at least one thread hangs on a `futex()` until _systemd_ gives up waiting for it and kills it with a `SIGKILL`.

This is pretty nasty behaviour and might actually be causing some of our intermittent test failures.

**Comment by jgrund** [comment]
@brianjmurrell Is this still an issue? The agent was refactored recently to use systemd instead of init and in the process dropped it's dependency on python-daemon.

**Comment by brianjmurrell** [comment]
@jgrund Not sure TBCH.  We can close this an reopen if it resurfaces.
