### ISSUE TITLE
Set hostid on hosts in EFS tests

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#296]
Now lustre is enforcing MMP, hostid needs to be present on hosts for monitored mode IML functionality. In order to use MMP with zpools, we need to set the hostid in existing filesystem tests.

**Comment by brianjmurrell** [comment]
Would users be able to create filesystems without `hostid`s?

**Comment by tanabarr** [comment]
yes , but with nondeterministic consequences as the zfs MMP mechanism would not work
this change has been integrated into #314 and merged
