### ISSUE TITLE
Consider implications of ZFS MMP prerequisites in monitored mode

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#297]
In IML monitored mode, we can only operate safely iif MMP Zfs is able to function correctly.

For this, _hostid_ s need to be set and _multihost_ property set on zpools.

Do we set either of those if not present or should we enforce checks before IML tries anything?

Obviously setting anything in monitored mode that would have side-effects on users system is not acceptable, and if IML, for example, imports pools in IML without the necessary ZFS MMP prerequisites being set we also risk side effects.

**Comment by brianjmurrell** [comment]
In monitored mode, we should do **nothing** that alters any configuration of anything to do with Lustre.

If users are able to set up filesystems that do not meet the requirements of IML, IML should refuse to work with them.

Any requirements of configuration of Lustre by IML needs to be detailed in the documentation.

The other option of course is to alter our methods to not have such requirements, if that is possible.
