### ISSUE TITLE
Re-enable (and fix) test_toggled_outlet_does_not_trigger_fencing_update in ssi test suite

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#311]
test_toggled_outlet_does_not_trigger_fencing_update (tests.integration.shared_storage_configuration.test_power_control.TestHostFencingConfig) disabled/skipped #341 in ssi test suite due to #315 . Investigate this failure and find a fix so it can be re-enabled.

**Comment by brianjmurrell** [comment]
Is there a ticket opened on the actual failure that was being seen with this test?

**Comment by jgrund** [comment]
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1877/arch=x86_64,distro=el7/testReport/tests.integration.shared_storage_configuration.test_power_control/TestHostFencingConfig/test_toggled_outlet_does_not_trigger_fencing_update/

**Comment by jgrund** [comment]
Covered in #315

**Comment by brianjmurrell** [comment]
Reopening to track the fixing of #315 and reverting of #341.

**Comment by jgrund** [comment]
#341 has been reverted. At this point this issue is a dup of #315 I think.
