### ISSUE TITLE
CentOS 7 build problems

### ISSUE THREAD

**Issue by jn0** [intel-hpdd/intel-manager-for-lustre#343]
#### No `ed`(1)

`make` fails without obvious reason at `ed settings.py`.  
Some digging found lack of `ed` utility widely used here.

One have to `yum -y install ed` first.  
`command -v ed` may be useful to check prerequisites.  
Or add a `BuildRequires: ed` into a `spec` file...

#### Bad `setuptools` package installed via `yum` (way too old, I think)

One have to:
1. `sudo yum -y erase python-setuptools`
2. `sudo -H pip install setuptools`
3. comment out `BuildRequire: python-setuptools` in all the `spec` files

##### Yepp, no `pip` too.

1. `yum -y install python2 python-devel`
2. `curl -LOSs https://bootstrap.pypa.io/get-pip.py`
3. `python2 get-pip.py`

I'd add a check for `command -v pip` to the master `Makefile` too...

#### There is a set of dot-files that break the build

Add `%define _unpackaged_files_terminate_build 0` to `chroma-manager.spec` or try to cope with zero-sized files:
- `$RPM_BUILD_ROOT/usr/lib/python2.7/site-packages/.chroma-manager.py*`
- `$RPM_BUILD_ROOT/usr/lib/python2.7/site-packages/.production_supervisord.conf`
- `$RPM_BUILD_ROOT/usr/lib/python2.7/site-packages/.storage_server.repo`

These files are told to be a hackaround for that `setuptools` too...

#### Where is `libsystemd.po`?

Run `sudo yum install systemd-devel`...

#### No `libpq-fe.h`... 

Some PostgreSQL repo is required, I think... Yes.

Reading https://www.postgresql.org/download/linux/redhat/ one will find himself typing:
- `sudo yum install https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm`
- `sudo yum install postgresql96-devel`
because he wont deal with lame 9.2.23 packaged with CentOS.

Now try to propagate `-L/usr/pgsql-9.6/include` to where it builds `psycopg/psycopgmodule.o`...

#### No `graphviz/cgraph.h`...

`sudo yum install graphviz-devel` first...

#### `psycopg2` build errors

After dirty hack of `sudo ln -s ll /usr/pgsql-9.6/include/{libpq-fe.h,postgres_ext.h,pg_config_ext.h} /usr/pgsql-9.6/include/libpq -t /usr/include/` it could compile. Almost. Linker error for `-lpq`.

Well, the hack of
```
[root@jno lib]# ln -s /usr/pgsql-9.6/lib/libpq* -t /usr/lib64/
[root@jno lib]# ldconfig
```
RULEZZ! ;)

#### `createrepo: command not found`

It's easy: `sudo yum install createrepo`

#### No `ruby` here...

`sudo yum install ruby`, of course...

#### No dependency packages for `chroma-agent` plus something else

```
make[1]: Entering directory `/home/jno/intel-manager-for-lustre/chroma-bundles'
make TOP=/home/jno/intel-manager-for-lustre/chroma-bundles REPO=/home/jno/intel-manager-for-lustre/chroma-bundles/../chroma-dependencies/repo -C chroma-agent 
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `for p in python2-tablib python2-iml-common1.3 iml_sos_plugin iml-device-scanner dnf-command(repoquery) dnf; do echo "whatrequires $p:"; repoquery --repofrompath=myrepo,/home/jno/intel-manager-for-lustre/chroma-bundles/../chroma-dependencies/repo --disablerepo="*" --enablerepo=myrepo -q --whatrequires $p; echo "whatprovides $p:"; repoquery --repofrompath=myrepo,/home/jno/intel-manager-for-lustre/chroma-bundles/../chroma-dependencies/repo --disablerepo="*" --enablerepo=myrepo -q --whatprovides $p; done'
make[2]: Entering directory `/home/jno/intel-manager-for-lustre/chroma-bundles/chroma-agent'
../include/Makefile.bundle:7: 
../include/Makefile.bundle:8: *** Missing dependencies: python2-tablib python2-iml-common1.3 iml_sos_plugin iml-device-scanner dnf-command(repoquery) dnf.  Stop.
make[2]: Leaving directory `/home/jno/intel-manager-for-lustre/chroma-bundles/chroma-agent'
make[1]: *** [chroma-agent] Error 2
make[1]: Leaving directory `/home/jno/intel-manager-for-lustre/chroma-bundles'
make: *** [chroma-bundles] Error 2
```
and
```
[jno@jno intel-manager-for-lustre]$ sudo yum install python2-tablib python2-iml-common1.3 iml_sos_plugin iml-device-scanner dnf-command repoquery dnf
...
No package python2-tablib available.
No package python2-iml-common1.3 available.
No package iml_sos_plugin available.
No package iml-device-scanner available.
No package dnf-command available.
No package repoquery available.
No package dnf available.
Error: Nothing to do
[jno@jno intel-manager-for-lustre]$ 
```
The local repo it tries to use has these files:
```
[jno@jno intel-manager-for-lustre]$ ls chroma-dependencies/repo/
chroma-agent-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.noarch.rpm
chroma-agent-management-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.noarch.rpm
chroma-manager-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.x86_64.rpm
chroma-manager-cli-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.x86_64.rpm
chroma-manager-debuginfo-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.x86_64.rpm
chroma-manager-integration-tests-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.x86_64.rpm
chroma-manager-libs-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.x86_64.rpm
repodata
```

- `tablib` found in `pip` only
- `iml-common` and `iml_sos_plugin` found in `pip` and , of course, at https://github.com/intel-hpdd

Manual install using `pip` doesn't help.

- `iml-device-scanner` does not exist under this name, but https://github.com/intel-hpdd/device-scanner looks close enough (**I dunno how to build it**).

- `dnf-command` is **not** provided for CentOS 
- `repoquery` is provided by `yum-utils`, not `dnf-command`
- Fedora's `dnf` is **not** provided for CentOS 

~It sounds odd, but running `make TOP=/home/jno/intel-manager-for-lustre/chroma-bundles REPO=/home/jno/intel-manager-for-lustre/chroma-bundles/../chroma-dependencies/repo -C chroma-agent` alone works.~ Wrong dir.

It looks like the code
```Makefile
REPO         := $(patsubst %/,%,$(REPO))
ret          := $(shell python ../include/find_deps.py "$(REPO)" "$(RPMS)" "$(EXCLUDES)" 2>/dev/null; echo "rc=$$?")
.SHELLSTATUS := $(subst rc=,,$(lastword $(ret)))
BUNDLE_RPMS  := $(filter-out rc=%,$(ret))
ifneq ($(.SHELLSTATUS), 0)
  foo := $(shell for p in $(BUNDLE_RPMS); do echo "whatrequires $$p:"; repoquery --repofrompath=myrepo,$(REPO) --disablerepo="*" --enablerepo=myrepo -q --whatrequires $$p; echo "whatprovides $$p:"; repoquery --repofrompath=myrepo,$(REPO) --disablerepo="*" --enablerepo=myrepo -q --whatprovides $$p; done)
  $(warning $(foo))
  $(error Missing dependencies: $(BUNDLE_RPMS))
endif
```
from `chroma-bundles/include/Makefile.bundle` will never work for me.
The call `python chroma-bundles/include/find_deps.py chroma-dependencies/repo chroma-agent-management lustre` returns `1` as exit code and
```
python2-tablib
python2-iml-common1.3
iml_sos_plugin
iml-device-scanner
dnf-command(repoquery)
dnf
```
as output.

But if you capture its stderr, you'll see:
```
  package selinux-policy-3.13.1-166.el7.noarch:
 requires python2-toolz:
 provided by {<YumAvailablePackageSqlite : python2-toolz-0.7.4-1.el7.noarch (0x4a87250)>: [u'python2-toolz']}:
  package python2-toolz-0.7.4-1.el7.noarch:
 requires python2-tablib:
 provided by {}:
```

I really have to fix that "requirements" and deal with "syntax error".

Ohh,,, went to fix `chroma-agent/chroma_agent/lib/yum_utils.py`.

### Repro

```
git clone https://github.com/intel-hpdd/intel-manager-for-lustre.git && make -C intel-manager-for-lustre
```

### Version

- What version of IML?  
Current one.
- What Operating System?  
Linux, CentOS 7 (initially: minimal)
- What Operating System version?  
```
[root@jno ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@jno ~]# uname -a
Linux jno.in.inbase.io 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by brianjmurrell** [comment]
We build hundreds of times a day on CentOS 7 and don't see any of these issues so it would be useful for us to understand what the differences are between our environment and yours to see what we can do to resolve your build issues and solidify the build process.

Could you attach a full log of your build so that I can see where it's going off the rails?

**Comment by Kmannth** [comment]
Brian I am having the same experience on Centos 7.4 
After installing ed the build still fails due to rpm packaging issues. 

Software is the top of git yesterday. 

Attached is what appears on the console during build. 
[build-fail.log](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1383341/build-fail.log)

**Comment by brianjmurrell** [comment]
What does `rpm -qa | grep setuptools` report for you?

**Comment by Kmannth** [comment]
rpm -qa | grep setuptools
python-setuptools-0.9.8-7.el7.noarch


cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

**Comment by brianjmurrell** [comment]
Does #344 get you any further in building?  Please attach another log if not.

**Comment by Kmannth** [comment]
I pulled 344 and it is still not building.  

[build-fail-344.log](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1383995/build-fail-344.log)

**Comment by brianjmurrell** [comment]
> I pulled 344 and it is still not building.

You need to manually remove `.storage_server.repo` from your top-level directory.

**Comment by Kmannth** [comment]
"
[root@ct7-adm intel-manager-for-lustre]# rm chroma-manager/.storage_server.repo
rm: remove regular empty file ‘chroma-manager/.storage_server.repo’? y
"

make ends with:
"
echo "jenkins_fold:end:Make requirements.txt"
jenkins_fold:end:Make requirements.txt
echo "jenkins_fold:start:Make Docs"
jenkins_fold:start:Make Docs
set -e;                                                         \
if [ -z  ] ; then                                 \
        virtualenv myenv;                                       \
        . myenv/bin/activate;                                   \
        pip install --upgrade pip;                              \
        pip install --upgrade setuptools;                       \
        pip install -Ur requirements.txt;                       \
fi;                                                             \
make -C docs/ && cp docs/dist/*.tar.gz dist/
/bin/sh: line 2: virtualenv: command not found
make[1]: *** [docs] Error 127
make[1]: Leaving directory `/home/vagrant/intel-manager-for-lustre/chroma-manager'
make: *** [chroma-manager] Error 2
"

There are a lot of warnings from rpm commands. 

Looking into virutalenv.

**Comment by brianjmurrell** [comment]
You need to install _python-virtualenv_: `yum -y install python-virtualenv`.

**Comment by Kmannth** [comment]
What are all the packages I need to install to be able to make this project? 

There is some libsystemd error in python now. 
[build-fail-344-libsystemd.log](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1384076/build-fail-344-libsystemd.log)

**Comment by brianjmurrell** [comment]
> What are all the packages I need to install to be able to make this project?

That is a list that is going to have to grow organically as we get feedback from people trying to build such as you are.  An issue has been opened to create a doc to cover all of this.

> There is some libsystemd error in python now.

`yum -y install systemd-devel`

**Comment by Kmannth** [comment]
I am @ no libpq-fe.h file now.  I will follow comment #1 to resolve the next few issues...

**Comment by brianjmurrell** [comment]
> I am @ no libpq-fe.h file now. I will follow comment #1 to resolve the next few issues...

Please don't.  I don't think any of those solutions are needed.  Please post your latest build log so that I can assess what the problem is.

**Comment by brianjmurrell** [comment]
> I am @ no libpq-fe.h file now.

For that you should just need `yum -y install postgresql-devel`.

**Comment by Kmannth** [comment]
So far:
I stayed with the postgresds in the updates repo. 

yum install postgresql-devel
yum install graphviz-devel
yum install createrepo

Now there is a make process listing a few missing dependencies. 
[build-fail-missingdeps.log](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1384135/build-fail-missingdeps.log)

Looking into the non IML packages listed.

**Comment by brianjmurrell** [comment]
Ahh.  You need to have the [_manager-for-lustre_](https://copr.fedorainfracloud.org/coprs/managerforlustre/manager-for-lustre/) repo configured on your build machine:

```
# yum -y install yum-plugin-copr
# yum copr enable managerforlustre/manager-for-lustre
```

**Comment by Kmannth** [comment]
I also installed dnf but hitting this now.

[build-fail-344-dnf-command.log](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1384192/build-fail-344-dnf-command.log)

I will check back next week.

**Comment by brianjmurrell** [comment]
You also need the DNF repository:

```
# yum copr enable ngompa/dnf-el7
```

**Comment by kbuggenhout** [comment]
doing the same exercise at the moment, started with a fresh CentOS7.4 development workstation, only had to add epel, npm and dnf repo's, then had to install npm ( sudo yum install -y npm) . but now stuck at the end 

warning: File listed twice: /usr/share/chroma-manager/chroma-manager.py
warning: File listed twice: /usr/share/chroma-manager/chroma_help/__init__.py
warning: File listed twice: /usr/share/chroma-manager/chroma_help/__init__.pyc
warning: File listed twice: /usr/share/chroma-manager/chroma_help/__init__.pyo
warning: File listed twice: /usr/share/chroma-manager/chroma_help/help.py
warning: File listed twice: /usr/share/chroma-manager/chroma_help/help.pyc
warning: File listed twice: /usr/share/chroma-manager/chroma_help/help.pyo
warning: File listed twice: /usr/share/chroma-manager/manage.py
warning: File listed twice: /usr/share/chroma-manager/ui-modules/node_modules/@iml/old-gui/__init__.py
warning: File listed twice: /usr/share/chroma-manager/ui-modules/node_modules/@iml/old-gui/__init__.pyc
warning: File listed twice: /usr/share/chroma-manager/ui-modules/node_modules/@iml/old-gui/__init__.pyo
warning: File listed twice: /usr/share/chroma-manager/tests/integration/core/clear_ha_el6.sh
warning: File listed twice: /usr/share/chroma-manager/tests/integration/core/clear_ha_el7.sh
warning: File listed twice: /usr/share/chroma-manager/tests/integration/run_tests
error: Installed (but unpackaged) file(s) found:
   /usr/lib/python2.7/site-packages/.chroma-manager.py
   /usr/lib/python2.7/site-packages/.chroma-manager.pyc
   /usr/lib/python2.7/site-packages/.chroma-manager.pyo
   /usr/lib/python2.7/site-packages/.production_supervisord.conf
   /usr/lib/python2.7/site-packages/.storage_server.repo
    File listed twice: /usr/share/chroma-manager/chroma-manager.py
    File listed twice: /usr/share/chroma-manager/chroma_help/__init__.py
    File listed twice: /usr/share/chroma-manager/chroma_help/__init__.pyc
    File listed twice: /usr/share/chroma-manager/chroma_help/__init__.pyo
    File listed twice: /usr/share/chroma-manager/chroma_help/help.py
    File listed twice: /usr/share/chroma-manager/chroma_help/help.pyc
    File listed twice: /usr/share/chroma-manager/chroma_help/help.pyo
    File listed twice: /usr/share/chroma-manager/manage.py
    File listed twice: /usr/share/chroma-manager/ui-modules/node_modules/@iml/old-gui/__init__.py
    File listed twice: /usr/share/chroma-manager/ui-modules/node_modules/@iml/old-gui/__init__.pyc
    File listed twice: /usr/share/chroma-manager/ui-modules/node_modules/@iml/old-gui/__init__.pyo
    File listed twice: /usr/share/chroma-manager/tests/integration/core/clear_ha_el6.sh
    File listed twice: /usr/share/chroma-manager/tests/integration/core/clear_ha_el7.sh
    File listed twice: /usr/share/chroma-manager/tests/integration/run_tests
    Installed (but unpackaged) file(s) found:
   /usr/lib/python2.7/site-packages/.chroma-manager.py
   /usr/lib/python2.7/site-packages/.chroma-manager.pyc
   /usr/lib/python2.7/site-packages/.chroma-manager.pyo
   /usr/lib/python2.7/site-packages/.production_supervisord.conf
   /usr/lib/python2.7/site-packages/.storage_server.repo
make[1]: *** [rpms] Error 1
make: *** [chroma-manager] Error 2

**Comment by kbuggenhout** [comment]
I have only the following artefacts built in the dist directory : 
[kb@localhost intel-manager-for-lustre]$ ls -l dist
total 296
-rw-rw-r-- 1 kb kb 162756 Oct 15 18:34 chroma-agent-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.noarch.rpm
-rw-rw-r-- 1 kb kb  89812 Oct 15 18:34 chroma-agent-4.0.0.0.tar.gz
-rw-rw-r-- 1 kb kb  46800 Oct 15 18:34 chroma-agent-management-4.0.0.0-4961.56.g99d7a77.jenkins__.el7.noarch.rpm

**Comment by kbuggenhout** [comment]
by adding the suggested 
%define _unpackaged_files_terminate_build 0 
to chroma_manager.spec

and graphviz-devel, graphviz-python

and got a successfull build.

will try again from a vanilla centos 7.4 development workstation and see the minimal changes needed.
I suspect it will be only the definition for 0 sized files graphviz-devel/python, epel repo, dnf repo and npm to get to a successfull compile.

**Comment by jn0** [comment]
plz note, that PostgreSQL from RPM is barely useful!
In case you want to use it in any other way (than this build), you have to install a better version.

**Comment by jn0** [comment]
Right now my built stuck at this phase:

[fail.log](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1386634/fail.log)

**Comment by jn0** [comment]
Quite strange to see `ld` problems when `ldconfig` looks aware of `libpq`:
```
[jno@jno intel-manager-for-lustre]$ ldconfig -p | grep pq
	libpqwalreceiver.so (libc6,x86-64) => /usr/pgsql-9.6/lib/libpqwalreceiver.so
	libpq.so.5 (libc6,x86-64) => /usr/pgsql-9.6/lib/libpq.so.5
	libpq.so (libc6,x86-64) => /usr/pgsql-9.6/lib/libpq.so
[jno@jno intel-manager-for-lustre]$ 
```

**Comment by jn0** [comment]
Well, even the hack of
```
[root@jno ~]# cd /usr/pgsql-9.6/lib
[root@jno lib]# ln -s libpq* -t /usr/lib64/
[root@jno lib]# ldconfig
```
gimmi nothing.
Giving up :(

**Comment by jn0** [comment]
And I do have that `psycopg2` already installed:
```
[root@jno lib]# pip install psycopg2
Requirement already satisfied: psycopg2 in /usr/lib64/python2.7/site-packages
[root@jno lib]# 
```

**Comment by brianjmurrell** [comment]
> by adding the suggested
> %define _unpackaged_files_terminate_build 0
> to chroma_manager.spec
> ...
> and got a successfull build.

Yes, this is one solution, but it's not the correct solution.  This just disables a consistency check in the RPM build process, rather than fixing the consistency problem.

**Comment by brianjmurrell** [comment]
> plz note, that PostgreSQL from RPM is barely useful!

It's working just fine for the purposes for which it is needed.  If you can demonstrate a case where it's not working that is relevant to IML, we will definitely reconsider, but in this case it's working as advertised.

**Comment by brianjmurrell** [comment]
@jn0 A standard CentOS 7 machine doesn't have `/usr/pgsql-9.6/`:

```
$ ls -l /usr/pgsql-9.6/         
ls: cannot access /usr/pgsql-9.6/: No such file or directory
```

so you must be trying to build against a version of PostgreSQL that does not come from CentOS.  I'm afraid there is not much I'm going to be able to do to help you figure out what you need to do to get IML to build against a non-CentOS supplied PostgreSQL, but if you manage to come up with a patch which will build against a non-CentOS supplied PostgreSQL **and** continue to build against the CentOS supplied PostgreSQL, we will be happy to look at it in regards to landing it.

**Comment by jn0** [comment]
I have to fix `chroma-agent/chroma_agent/lib/yum_utils.py` and its `spec`...

**Comment by jn0** [comment]
@brianjmurrell yes, any "clean" CentOS has no pgsql-9.6.

It has no PostgreSQL installed at all.
So, it's up to you which one to install, right?
I've installed 9.6 from an official build (because I have a bad experience using 9.2 a year ago).

Right now I used a dirty hack symlinking headers and libs to where the `pip`-built commands are looking for their stuff.

I have a plan:
1. get the build to finish w/o errors
2. get a working build
3. think about unhacking my hacks (and publish any found solutions)

That tambourine dance with PgSQL is no major problem.
Anybody may have 9.2 installed "just to build".

**Comment by jn0** [comment]
@brianjmurrell as of `%define _unpackaged_files_terminate_build 0`.

It looks a lesser evil to me: 1 line to add at the head vs find where to remove 5 files :)

BTW, those files were introduced on purpose: it's commented in the code.

**Comment by brianjmurrell** [comment]
> It looks a lesser evil to me: 1 line to add at the head vs find where to remove 5 files :)

It's not a lesser evil.  Removing checks and balances is a sure fire way to introduce regressions.  LoC count is completely orthogonal here.  More LoC is not a bad thing when it fixes a problem in the correct manner.

> BTW, those files were introduced on purpose: it's commented in the code.

Yes, introduced a long time ago as a work-around needed at the time.  It's not at all improbable that the issue that they were introduced to work-around is no long relevant and so they can be removed.  The point of #344 is to test that theory.  It builds and tests fine in our build/test farm fine and is fixing build problems for people here in this issue.

Of course, the more environments we can confirm (or refute) that fix in the better.

**Comment by jn0** [comment]
@brianjmurrell it's not about LoC, it's about a set of files intentionally created and left over.

I don't [right now] feel me strong enough to surely remove them (well, I have an "educated guess"). And I don't want to do it abruptly.

Folks, I just started "mein kampf" trying just to make it to build in my [hostile] environment :)

If my bosses give me some time, I promise to make _good fix_ for IML-in-CentOS!

**Comment by jn0** [comment]
Right now I'm "polimorphing" `yum_utils.py` to allow non-dnf world to be covered...

**Comment by brianjmurrell** [comment]
> Right now I'm "polimorphing" yum_utils.py to allow non-dnf world to be covered...

We use DNF because YUM's dependency resolver is not smart enough to deal with the mixed dkms/kmod packaging of Lustre.

**Comment by jn0** [comment]
yes, but I stuck with yum so far:
```
[root@jno ~]# yum install dnf
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.yandex.ru
 * epel: fedora-mirror01.rbc.ru
 * extras: mirror.corbina.net
 * updates: mirror.corbina.net
No package dnf available.
Error: Nothing to do
[root@jno ~]# 
```

**Comment by jn0** [comment]
Different sources (https://www.rootusers.com/how-to-install-dnf-package-manager-in-centosrhel/ for instance) insist on `yum install epel-release && yum install dnf`, but I do have `epel-release`:
```
[root@jno ~]# yum -C list installed | grep ^epel
epel-release.noarch                 7-10                               @epel    
[root@jno ~]# 
```
and still have no `dnf`.

Something has changed.

**Comment by brianjmurrell** [comment]
> yes, but I stuck with yum so far:

Are you following the (admittedly, still evolving thanks to this ticket) [build documentation ticket](https://github.com/intel-hpdd/Online-Help/issues/27) or the direction in [this previous comment](https://github.com/intel-hpdd/intel-manager-for-lustre/issues/343#issuecomment-336592040) to get DNF?

**Comment by jn0** [comment]
No, I missed `yum copr enable ngompa/dnf-el7` recipe.

I'll try it now.

**Comment by jn0** [comment]
I think, I have to reset my build machine to it's initial state (almost pure CentOS minimal) and then try again.

**Comment by jn0** [comment]
Hm, I cannot even follow the recipe:
```
[root@jno ~]# yum copr enable ngompa/dnf-el7
Loaded plugins: fastestmirror
No such command: copr. Please use /usr/bin/yum --help
[root@jno ~]# 
```

**Comment by jn0** [comment]
`yum install yum-plugin-copr` must be performed...

**Comment by brianjmurrell** [comment]
Thanks.  Reordering the steps got that out of sync.  Updated.

**Comment by jn0** [comment]
Well, it _looks_ built.

With [my.patch.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1387976/my.patch.txt) applied (actually, one may leave `Makefile` intact) and [iml-prereq.sh.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1387977/iml-prereq.sh.txt) executed, it works.

This is what was installed on the box **before** [installed-1.lst.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1387992/installed-1.lst.txt) and **after** [installed-2.lst.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1387994/installed-2.lst.txt)

Actually, **this** topic is about to close...

**Comment by jn0** [comment]
JFYI: I have this set of files in `dist`:
```
[jno@node10 intel-manager-for-lustre]$ ll dist/
total 8304
-rw-rw-r--. 3 jno jno  162656 Oct 16 18:14 chroma-agent-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.noarch.rpm
-rw-rw-r--. 1 jno jno   89812 Oct 16 18:10 chroma-agent-4.0.0.0.tar.gz
-rw-rw-r--. 3 jno jno   46904 Oct 16 18:14 chroma-agent-management-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.noarch.rpm
-rw-rw-r--. 1 jno jno  105020 Oct 16 18:14 chroma-cluster-sim-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.centos.noarch.rpm
-rw-rw-r--. 1 jno jno   46432 Oct 16 18:14 chroma-cluster-sim-4.0.0.0.tar.gz
-rw-rw-r--. 3 jno jno 3106696 Oct 16 18:14 chroma-manager-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.x86_64.rpm
-rw-rw-r--. 1 jno jno 3766554 Oct 16 18:10 chroma-manager-4.0.0.0.tar.gz
-rw-rw-r--. 3 jno jno   41832 Oct 16 18:14 chroma-manager-cli-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.x86_64.rpm
-rw-rw-r--. 2 jno jno    1904 Oct 16 18:11 chroma-manager-debuginfo-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.x86_64.rpm
-rw-rw-r--. 2 jno jno  229780 Oct 16 18:11 chroma-manager-integration-tests-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.x86_64.rpm
-rw-rw-r--. 3 jno jno   13892 Oct 16 18:14 chroma-manager-libs-4.0.0.0-4962.57.g3e3cf91.jenkins__.el7.x86_64.rpm
-rw-rw-r--. 1 jno jno  527067 Oct 16 18:14 manager-doc-internals.tar.gz
-rw-rw-r--. 1 jno jno   68518 Oct 16 18:14 manager-doc-packaging.tar.gz
-rw-rw-r--. 1 jno jno  101322 Oct 16 18:14 manager-doc-rest-api.tar.gz
-rw-rw-r--. 1 jno jno   68018 Oct 16 18:14 manager-doc-scheduler-plugin-api.tar.gz
-rw-rw-r--. 1 jno jno   97094 Oct 16 18:14 manager-doc-storage-plugin-api.tar.gz
[jno@node10 intel-manager-for-lustre]$ 
```

**Comment by Kmannth** [comment]
The install documentation assumes there is an iml-4.0.0.0.tar file or similar.  What is the next step from the software in dist to the tarball release?

**Comment by brianjmurrell** [comment]
@Kmannth Let's restrict this ticket to just the process of building the IML RPMs and please open a new ticket about taking the result of building those to get the _iml-*.tar.gz_ tarball.  TIA.

**Comment by jgrund** [comment]
I'm assuming the purpose of this issue is to build IML from source to an installable tarball. However, just a PSA for anyone just looking to install: The catalog of released 4.0 versions is available here: https://github.com/intel-hpdd/intel-manager-for-lustre/releases.

Each one has a tarball that is the end result of these processes.

**Comment by jn0** [comment]
BTW, I'd like a fix to build process to handle pgsql installed from **[official repos](https://www.postgresql.org/download/linux/redhat/)**.

They go to `/usr/pgsql-X.Y` and that's **right!**  
Because of migration process.  
When you're about to upgrade your pgsql from M.N to X.Y you must have **both** installed!  
The scheme given by the PostgreSQL community serves this need well.

BTW, they provide valid set of `lib/pkgconfig/*.pc` files to work with `pkg-config` tool.  
But they're ignored (in `pip` builds at least)...

**Comment by brianjmurrell** [comment]
> BTW, I'd like a fix to build process to handle pgsql installed from official repos.

This is not something that is on our own development roadmap but we are always happy to evaluate patches for inclusion.  Such a patch must preserve the existing behaviour of using the distro supplied PostgreSQL from RPM if that is what is installed.

**Comment by jn0** [comment]
ok

**Comment by jgrund** [comment]
Selected fixes landed in https://github.com/intel-hpdd/intel-manager-for-lustre/pull/344

**Comment by kbuggenhout** [comment]
@brianjmurrell just confirmed, removing the empty storage_repo file did the trick, after enabling the dnf repo etc. reset my testbuilding maching to CentOS7.4 with Development package group installed, then pulled a fresh copy with git, ran make.
the only thing I was missing was the npm package.

artefacts built : 

[kb@localhost intel-manager-for-lustre]$ ls dist
chroma-agent-4.0.0.0-4965.60.ge70642e.jenkins__.el7.noarch.rpm
chroma-agent-4.0.0.0.tar.gz
chroma-agent-management-4.0.0.0-4965.60.ge70642e.jenkins__.el7.noarch.rpm
chroma-cluster-sim-4.0.0.0-4965.60.ge70642e.jenkins__.el7.centos.noarch.rpm
chroma-cluster-sim-4.0.0.0.tar.gz
chroma-manager-4.0.0.0-4965.60.ge70642e.jenkins__.el7.x86_64.rpm
chroma-manager-4.0.0.0.tar.gz
chroma-manager-cli-4.0.0.0-4965.60.ge70642e.jenkins__.el7.x86_64.rpm
chroma-manager-debuginfo-4.0.0.0-4965.60.ge70642e.jenkins__.el7.x86_64.rpm
chroma-manager-integration-tests-4.0.0.0-4965.60.ge70642e.jenkins__.el7.x86_64.rpm
chroma-manager-libs-4.0.0.0-4965.60.ge70642e.jenkins__.el7.x86_64.rpm
manager-doc-internals.tar.gz
manager-doc-packaging.tar.gz
manager-doc-rest-api.tar.gz
manager-doc-scheduler-plugin-api.tar.gz
manager-doc-storage-plugin-api.tar.gz
