### ISSUE TITLE
Document process to make tarball release 

### ISSUE THREAD

**Issue by Kmannth** [intel-hpdd/intel-manager-for-lustre#349]
### Description 
Jira ticket "CentOS 7 build problems  #343" worked out the process of making the software. 

Intel ML install instructions start with IML-4.0.0.0.tar (a tarball software release) but this is not produced by the make process.  

Please document how to make the release tarball 
 
### Repro

Follow the needed steps to make from git and observe there is no release tarball as described as the starting point for installation of software. 

### Version

What version of IML? IML current Master +  commit c12fb35ca99296711ccef50b1147ca84626b02a0 + commit 6c7f7cbd3970acb0ae2bc4744012a30a96638981

What Operating System? Centos 7.4
What Operating System version? Centos 7.4

**Comment by jgrund** [comment]
Moved to https://github.com/intel-hpdd/Online-Help/issues/29
