### ISSUE TITLE
Where to get the usable storage plugin for CentOS 7.4 with SATA disk?

### ISSUE THREAD

**Issue by guoguixin** [intel-hpdd/intel-manager-for-lustre#351]
### Description 

I'm currently using virtualbox to install IML. The manager frontend was successfuly installed(running on CentOS 7.4) and I have use "add server" to add 2 virtualbox vm(CentOS 7.4). But after that in the frontend's storage tab, it complained no storage plugin was installed. So that I can not create MGT because no storage can select for create it. I'm using Virtualbox 5.1.22 and each vm has attach a 20GB SATA virtual disk.

### Repro

After install IML and add 2 vm.

### Version

What version of IML?
IML 4.0.0.0RC1
What Operating System?
CentOS
What Operating System version?
CentOS 7.4.1708

**Comment by jgrund** [comment]
Hi @guoguixin,

The storage tab is used as a frontend for custom storage plugins; you don't need to reference it to create a fs.

Please see this doc starting here for a reference of how to create a managed fs: https://intel-hpdd.github.io/Online-Help/docs/Creating_new_lustre_fs_3_0.html#3.4

The order of setup for a new managed Lustre FS is:

1. configuration/servers
   - Deploy selected servers.
2. configuration/volumes 
  - Confirm primary / failover is as expected
3. configuration/Power Control 
  - Setup PDU's / IPMI for each server.
4. configuration/File Systems
  - Select MGT MDTs and OSTs and create the fs.

**Comment by jgrund** [comment]
Closing, this let us know if you need further help.
