### ISSUE TITLE
IML dialog boxes use iml-diagnostics instead of chroma-diagnostics

### ISSUE THREAD

**Issue by yhamidi** [intel-hpdd/intel-manager-for-lustre#355]
### Description 

Encountered An Error dialog box still uses chroma-diagnostics. Should be iml-diagnostics

### Version
IML 4.0

![screen shot 2017-10-20 at 6 00 52 am](https://user-images.githubusercontent.com/27026630/31829516-582d62b6-b572-11e7-8a3e-627d0b74cd5d.png)

**Comment by petertix** [comment]
Moved this issue into the GUI repo.
https://github.com/intel-hpdd/GUI/issues/106
