### ISSUE TITLE
Update coverage to not pull from dropbox

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#36]
We currently have a patched version of coverage hosted here:

https://dl.dropboxusercontent.com/s/qqjud11bvh8vo68/coverage-3.5.2pl2.tar.gz

We should not be using a personal dropdox as a dependency store.

Two approaches.

1. Try to use an unpatched version of coverage to pass tests.
2. Push the patched version to a registry such as Pypi.

**Comment by brianjmurrell** [comment]
Also worth looking at the patch(es) to see if it's obvious why we use them.

**Comment by tanabarr** [comment]
@chrisgearing has mentioned that he thinks the reasons for pulling coverage from dropbox and patching are historical and probably not relevant any more. therefore it's likely pulling the upstream version from epel will suffice.

**Comment by chrisgearing** [comment]
HYD-3335 is the ticket.

https://jira.hpdd.intel.com/browse/HYD-3335
https://review.whamcloud.com/#/c/10923/

**Comment by jgrund** [comment]
So, that ticket is due to an internal network issue, which may indeed no longer be an issue.

I assume we were previously pulling from: https://github.com/kprantis/coverage/archive/3.5.2pl2.tar.gz

Still have the open issue if we need to use patched version.
