### ISSUE TITLE
chroma-diagnostics needs to be Obsoletes:'d

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#374]
After an upgrade to 4.0, _chroma-diagnostics_ still exists.  It should be obsoleted.  Or better yet, it should refer the user to _iml-diagnostics_.

- [x] implement command to explain chroma-diagnostics is now iml-diagnostics.
- [x] test upgrading from 3.1.1 to 4.0.1
   - [x] verify chroma-diagnostics has been uninstalled (yum info chroma-diagnostics)
   - [x] verify iml-diagnostics runs correctly
   - [x] verify running chroma-diagnostics displays a message to the user indicating that it has been deprecated.
- [x] remove zfs from plugin section in iml_sos_report
- [x] publish new RPM version to COPR.
- [x] obsolete chroma-diagnostics.
- [x] #386 update [installation_and_upgrade](https://github.com/intel-hpdd/intel-manager-for-lustre/tree/master/chroma-manager/tests/framework/integration/installation_and_upgrade) test to verify replacement: https://github.com/intel-hpdd/intel-manager-for-lustre/pull/386

**Comment by jgrund** [comment]
To clarify, the approach for the second point is to put a "binary" that just prints to stdout to use iml-diagnostics instead.

**Comment by brianjmurrell** [comment]
intel-hpdd/iml_sos_plugin#7 implements the referral to _iml-diagnostics_ but this cannot close until the [iml_sos_plugin RPM spec](https://github.com/intel-hpdd/manager-for-lustre-dependencies/blob/master/iml_sos_plugin/iml_sos_plugin.spec) is updated to `Obsoletes: chroma-diagnostics`.

**Comment by johnsonw** [comment]
To test this on my vagrant box, I installed a clean version of IML@4.0.0 and ran chroma-diagnostics:
```
[root@adm iml_sos_plugin]# chroma-diagnostics
-bash: chroma-diagnostics: command not found
```

After verifying that the command doesn't exist, I packaged the iml_sos_plugin@2.0.4 and built an rpm from the package on my vagrant node using the following command:
```
rpmbuild -bb --define 'epel 1' --define '_srcrpmdir /repos/manager-for-lustre-dependencies/iml_sos_plugin' --define '_sourcedir /repos/manager-for-lustre-dependencies/iml_sos_plugin' /repos/manager-for-lustre-dependencies/iml_sos_plugin/iml_sos_plugin.spec
```

This generated an rpm file here: /root/rpmbuild/RPMS/noarch/iml_sos_plugin-2.0.4-1.el7.centos.noarch.rpm. I then ran "yum install /root/rpmbuild/RPMS/noarch/iml_sos_plugin-2.0.4-1.el7.centos.noarch.rpm". This installed the new version of iml_sos_plugin. I then ran the following:

```
[root@adm noarch]# yum info iml_sos_plugin
Loaded plugins: fastestmirror, langpacks
Repository extras is listed more than once in the configuration
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirror.cogentco.com
 * epel: mirror.steadfast.net
 * extras: ftp.usf.edu
 * updates: centos.vwtonline.net
Installed Packages
Name        : iml_sos_plugin
Arch        : noarch
Version     : 2.0.4
Release     : 1.el7.centos
Size        : 8.6 k
Repo        : installed
Summary     : A sosreport plugin for collecting IML data.
URL         : https://pypi.python.org/pypi/iml_sos_plugin
License     : MIT
Description : A sosreport plugin for collecting IML data.

[root@adm noarch]# chroma-diagnostics
chroma-diagnostics no longer exists. Please use 'iml-diagnostics' instead.
```

You can see that a message is generated when running "chroma-diagnostics," informing the user that this command no longer exists and that they should use iml-diagnostics instead.

**Comment by jgrund** [comment]
@brianjmurrell in the future, for overall tasks like these we should use checkbox notation instead of just comments

**Comment by johnsonw** [comment]
Regarding "obsolete chroma-diagnostics in the manager" I aded "Obsoletes  chroma-diagnostics" in the iml_sos_plugin spec file. Was this the wrong place to put it?

**Comment by brianjmurrell** [comment]
@johnsonw Yes, that is the right place to put it.

**Comment by brianjmurrell** [comment]
@jgrund Yes, checklists are a good idea.  I think when checking off an item in the list, the developer should add a link to the change that completes that item, if applicable.

**Comment by johnsonw** [comment]
All items checked off. I think we can close this issue now unless there are any objections.
