### ISSUE TITLE
Vagrantfile settings for shared folder synchronisation

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#375]
This issue does not necessarily require a change in version controlled source but should be recorded for informational purposes.

Affects virtualbox providers run by vagrant.

https://github.com/hashicorp/vagrant/issues/7157
by default vagrant will only use rsync to take a snapshot of a shared folder with our environment/setup. meaning we won't have access to real-time shared folder changes in our guest OS (at least this is the behaviour with virtual box running on Windows for me)

adding the following will result in mounting the shared folder rather than using rsync, giving access to real-time shared folder changes in the guest (notice the _type_ parameter appended to the config option)

`config.vm.synced_folder ".", "/vagrant", type: "virtualbox"`

**Comment by OPSJono** [comment]
I've just come across this exact issue.

We had a Vagrantfile which had only ever been written to work with Virtualbox.
I was making it work with virtmanager too.

Setup virtmanager to use NFS,
Then I noticed when regression testing the virtualbox setup, it was also trying to use NFS/rsync.

I've spent the past hour or so looking for documentation on what the value is for the "default" method of sharing folders is for virtualbox.

As you've pointed out here, "virtualbox" is the correct value.
It's also referenced many times [here](https://github.com/hashicorp/vagrant/issues/7157) in the comments.

I think this should certainly be added to the documentation of the Virtualbox section in Synced Folder [here](https://www.vagrantup.com/docs/synced-folders/virtualbox.html)

**Comment by jgrund** [comment]
@tanabarr @OPSJono, In our case this issue is actually our base `Vagrantfile` has been hardcoded to rsync. We should remove that and let Vagrant figure that out. 

I've opened: https://github.com/intel-hpdd/Packer-templates/pull/7 to fix this.
