### ISSUE TITLE
design a new test for pushing changes to the manager-for-lustre-dependencies repo

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#38]
Currently, before I push a change to the [manager-for-lustre-dependencies repo](https://github.com/intel-hpdd/manager-for-lustre-dependencies) I do a local build of it with something like:

```
$ cd manager-for-lustre-dependencies/nodejs
$ rpmbuild -bs --define epel\ 1 --define _sourcedir\ $PWD *.spec && mock ~/rpm/SRPMS/nodejs-6.10.2-1.01.el7.centos.src.rpm
```

We should have a way of testing such a thing as a CI test when a patch is pushed to the [manager-for-lustre-dependencies repo](https://github.com/intel-hpdd/manager-for-lustre-dependencies) as a review process.

Even though he should do such a thing as a part of sanity testing what he is pushing for review, we shouldn't assume and depend on the developer doing that test himself before pushing a patch.

Could investigate using [Copr](https://copr.fedorainfracloud.org/) for this.

**Comment by jgrund** [comment]
Fixed in manager-for-lustre-dependencies repo with travis integration
