### ISSUE TITLE
Move to reactive architecture for Devices + ZFS - Part 2

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#414]
## Background

Following on from #280 , we can derive all the necessary information required by the Resource Manager in IML from the output of the device scanner rather than the previous approach of manual introspection to discover device info + ZFS pool / dataset info and props.

As we look to scale and for generally not implementing redundant code that is implemented at the OS level, we should move to a push-based architecture.

Given this is effectively flipping the process of state discovery on it's head; it's something that should be attempted in phases. This issue will cover the 2nd phase.

## Implementation

The device tree that will represent the view of devices on each IML monitored or managed server will contain an in memory state for each host. This database can then be queried later to provide more structured views.

The envisaged concept is that the agent provides the device scanner output as ingress to the persistent device tree on manager and the resource manager is a consumer of the device tree. The resource manager then processes the device tree in to ORM model representation.

The device scanner listens to zed/udev events as input and output is currently consumed by the agent, instead of this we want something to transmit device-scanner output to manager (via nginx), which will initially be a separate process. The purpose of this `scanner-proxy` is to forward updates from the `device-scanner` stream in a transactional manner to the listening `device-aggregator` over HTTPS, required capability is to both listen on the `device-scanner` socket for any newline-delimited JSON objects (persistent connection) and then transmit these objects to the aggregator authenticated over HTTPS. 

The `device-aggregator` on manager host will update the global view of devices (state) when data is transmitted from the `scanner-proxy`. On receipt of the 'Info' command, the aggregator will return its current state.

The device-aggregator will host connections from multiple authenticated agents/device-scanners

Whilst approaches outlined in article such as https://thwadi.blogspot.com/2014/02/quick-and-dirty-command-bus-with-f.html seem very attractive, we may not need that level of flexibility given this is basically peer-to-peer and only one consumer will exist. Also, given we already have the capabilities provided by node (which we will be running on) we don't need to use the mailboxProcessor event architecture.

## Work Currently Needed

- [x] agent software component to forward device scanner information stream over HTTP to the manager
  - [x] device-scanner changes to enable streaming mode
    - [x] approved reviews
    - [x] landed to master
  - [x] scanner-proxy to forward device-scanner updates https://github.com/intel-hpdd/scanner-proxy/pull/1
    - [x] listen on socket for device-scanner updates (persistent connection)
    - [x] client connection to device aggregator over HTTPS and send on receipt of data over socket
    - [x] approved reviews
    - [x] landed to master

____

- [x] device-aggregator software component to listen and receive stream from agents (use existing agent certificate infrastructure for authorisation) https://github.com/intel-hpdd/device-aggregator/pull/3
  - [x] handler methods to store and retrieve current mappings between hostname and devices
  - [x] server to listen on GET and POST authenticated requests and call relevant handler methods
  - [x] manager nginx configuration updated to forward connections to the device-aggregator https://github.com/intel-hpdd/intel-manager-for-lustre/pull/432 - waiting on review and test
    - [x] approved reviews
    - [-] landed to master (will be landed as part of Part 3)
  - [x] rename modules inside IML namespace
  - [x] build scripts
  - [x] Vagrantfile
  - [x] CR updates
  - [x] update to fable bindings
  - [x] integration tests
  - [x] approved reviews
  - [x] landed to master

**Comment by brianjmurrell** [comment]
> if we have a "global view" that is presuming that shared drives are accessible via identical paths, is this not too simplistic and likely not to work in some real-life scenarios?

As long as we are not using paths that are specific and in particular to the node, we should be able to make this assumption.  `/dev/disk/by-id/` would be a consistent path across machines however `/dev/disk/by-path/` would not be, for example.
