### ISSUE TITLE
How to change IML MDT configuration when restore MDT with a new device

### ISSUE THREAD

**Issue by wutaizeng** [intel-hpdd/intel-manager-for-lustre#429]
### Description 

I use doc http://doc.lustre.org/lustre_manual.xhtml#dbdoclet.restore_target_filesystem to restore MDT with a new device, but i don't know how to change IML configuration about MDT

### Repro

1. backup MDT mount with ldiskfs type
2. restore MDT with a new device
3. I can manual to mount MDT, but can not start MDT in IML, because it's configuration have not changed to use new device

### Version

What version of IML?

4.0.0.0

What Operating System?

RHEL 

What Operating System version?

7.4

**Comment by tanabarr** [comment]
hello, could I ask whether you are using IML in managed or monitored mode (the profile you used when installing the servers in the UI)?

**Comment by wutaizeng** [comment]
managed mode

**Comment by tanabarr** [comment]
can I also please request the error messages/symptoms of failure you are seeing when you try to start the modified MDT?

**Comment by tanabarr** [comment]
so I can replicate your issue locally, please attach the sos-report (IML diagnostics) as per the documentation: https://intel-hpdd.github.io/Online-Help/docs/Install_Guide/ig_ch_16_appD_getting_help.html

**Comment by tanabarr** [comment]
just for your information we are planning to integrate this feature (target device change) into the project so if you're interested in helping move this along then providing more information would help. many thanks
