### ISSUE TITLE
make operations in IML packages fail due to missing macro file dependencies

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#433]
Calling `make requirements.txt` from within directory extracted from _chroma-manager-XXX.tar.gz_ will fail because it depends on `../include/Makefile.version` .

Using these make operations within IML packages for cluster-sim chroma-manager chroma-agent and chroma-diagnostics will fail unless used in a clone of the entire IML repo due to the dependency on the top-level "include" directory.

Solutions include 
* documenting this fact
* duplicating Makefile.version and any other dependencies from the top level include directory into the relevant subdirectories
* in-lining relevant code where relevant
* finding another method of retrieving version information

**Comment by jgrund** [comment]
I'm not sure this is a scenario we should spend time supporting.

If someone was to run `make requirements.txt` then they are necessarily doing a dev style setup.

I'd be more inclined to remove the `Makefile` (if we don't depend on it directly in the artifact) than support this.

**Comment by brianjmurrell** [comment]
This is all being reworked with the modularization effort.
