### ISSUE TITLE
Intel Manager crashes after reboot

### ISSUE THREAD

**Issue by Libeccio84** [intel-hpdd/intel-manager-for-lustre#434]
### Description 
I installed IML before creating a lustre fs.
After a clean reboot IML crashes and is no more reachable via https.
I am running IML on a Centos 7.4 VM, with xfs filesystem. No lustre servers (MGS, MDS or OSS have been created yet).

Here is what I get from the web interface:

####################
[description]
The following services are not running: 
corosync
gunicorn
http_agent
job_scheduler
lustre_audit
plugin_runner
power_control
realtime
stats
syslog
view_server

[debug]
server time: 2018-01-04T09:42:47.710Z
build: 4995
version: 4.0.2.0
is release: true
fqdn: iml.floffice.int
sysname: x86_64
nodename: iml.floffice.int
release: 3.10.0-693.el7.x86_64
version: Linux
machine: #1 SMP Tue Aug 22 21:09:27 UTC 2017
####################

Shall someone help me?

Thanks in advance

**Comment by Libeccio84** [comment]
I found the solution: it looks like I have to manually run
`chroma-config restart`
Is there a way to have the IML server up and running after any reboot?

**Comment by jgrund** [comment]
Hi @Libeccio84,

thanks for the report; IML should start at boot-time.

can you attach a sos-report from the manager node?

Once you so we can investigate further.

**Comment by jgrund** [comment]
Instructions for running `iml-diagnostics` can be found here:

https://intel-hpdd.github.io/Online-Help/docs/Install_Guide/ig_ch_16_appD_getting_help.html#run-iml-diagnostics

**Comment by Libeccio84** [comment]
Here it is, I have to mention that now the only two errors are for realtime and view_server.
[sosreport-iml.floffice.int-20180104171318.tar.xz.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1603938/sosreport-iml.floffice.int-20180104171318.tar.xz.zip)

Many thanks for the fast reply.

**Comment by Libeccio84** [comment]
I re-installed it on another server, it looks like it works now.
Close the issue if you think so.
Many thanks.

**Comment by jgrund** [comment]
I'm seeing `IntegrityError: FQDN mgs1.floffice.int in use` in the SOS report.

Could be the services we're coming up at boot, though incompletely.

Going to close as you've got this working.

**Comment by Libeccio84** [comment]
Many thanks.
