### ISSUE TITLE
Failed to configure corosync due to network decoding errorr

### ISSUE THREAD

**Issue by weijianwen** [intel-hpdd/intel-manager-for-lustre#438]
### Description 

I failed to configure corosync for a newly setup Lustre cluster via Intel Lustre Manager. Errror messages said “RuntimeError: Error reading from the network: Error decoding network packet: 'Data' object has no attribute 'get_uh_dport'”. A screen shot and full error messages are listed below.

### Repro

1. Install Client servers with CentOS 7.4, along with in-kernel Mellanox Infiniband driver, firewalld.
2. Configure IP addresses for Ethernet port and Infiniband port, for management and data separately. Bring up a “heartbeat” Ethernet port connected to the failover peer via a crossover cable. According to #245, this initial IP address should be 0.0.0.0 (unconfigure).
3. Add servers as Managed Storage Servers.
4. Configure CoroSync for the servers.

### Version

What version of IML? 4.0.2 (I am not quite sure about that since I find no where to check the IML version I am using.)
What Operating System? CentOS
What Operating System version? 7.4.1408

```
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run
    result = self.manager._session._client.action_plugins.run(self.action, agent_daemon_context, self.args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 303, in run
    return fn(**args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_corosync_common.py", line 32, in get_corosync_autoconfig
    ring1 = detect_ring1(ring0, ring1_ipaddr, ring1_prefix)

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/corosync.py", line 126, in detect_ring1
    discover_existing_mcastport(iface, timeout = 30)

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/corosync.py", line 253, in discover_existing_mcastport
    str(e))

RuntimeError: Error reading from the network: Error decoding network packet: 'Data' object has no attribute 'get_uh_dport'
```

![d03a5521-d992-42e0-877d-220dbee703c0](https://user-images.githubusercontent.com/908249/34649741-dd581df8-f3ef-11e7-839d-10a311297f2a.jpeg)
![cc61f678-9863-46c2-a980-4e7caf808496](https://user-images.githubusercontent.com/908249/34649742-df040004-f3ef-11e7-8665-a51786052383.jpeg)

**Comment by brianjmurrell** [comment]
Can you attach an SOS report from both of the nodes in the HA pair where this failed?

**Comment by weijianwen** [comment]
Sure thing. Please find `iml-diagnostics` logs attached for node001 and node002.

Yet another Lustre cluster (namely "production") running in my cluster, with the same VLAN and the same subnet which are managed by IML 3.0.0. The production Lustre works well. Does it matter to this issue?

[sosreport-node001-2018010922521.tar.gz](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1615496/sosreport-node001-2018010922521.tar.gz)
[sosreport-node002-20180109225209.tar.gz](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1615497/sosreport-node002-20180109225209.tar.gz)

**Comment by brianjmurrell** [comment]
I suspect perhaps too much time went by after hitting the error and collecting the SOS report.

Can you reproduce this problem and collect the SOS reports right after it occurs please?

**Comment by weijianwen** [comment]
Thank you, @brianjmurrell .

I run `touch /tmp/chroma-agent-debug; systemctl restart chroma-agent` on every Lustre servers,  then tried to configure CoroSync, and collects SOS reports immediately hitting this issue. 

I found IML web UI insists on using UTC when displaying time, even though all Lustre servers and server where IML is running have been configured to CST timezone. That's why the timestamps look weird.

[sosreport-node002.pi.sjtu.edu.cn-20180112000010.tar.gz](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1623252/sosreport-node002.pi.sjtu.edu.cn-20180112000010.tar.gz)
[sosreport-node001.pi.sjtu.edu.cn-20180112000007.tar.gz](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1623253/sosreport-node001.pi.sjtu.edu.cn-20180112000007.tar.gz)

**Comment by brianjmurrell** [comment]
@weijianwen: Did you configure the _ib0_ interface on your storage servers with an IPv4 address before trying to add the nodes to IML?

I see that _ib0_ has an ip address of _10.0.3.1_ but it looks like IML set this address.  Is this case?  If so, you need to configure your I/B network addresses to the network that you wish Lustre to run on before trying to add the nodes to IML.

To be clear, IML does not configure your LNET interfaces with an IP address as the IP space that the Lustre filesystem should be available to Lustre clients in is going to be very site specific.  For that reason, IML expects the administrator to configure those interfaces and assign IP addresses before IML can add the nodes to IML, much like it expects _eth0_ to be pre-configured.
