### ISSUE TITLE
Cannot start filesystem

### ISSUE THREAD

**Issue by Libeccio84** [intel-hpdd/intel-manager-for-lustre#439]
Hi all,
I have recently installed IML and I have successfully added 3x2 servers (HA) with iscsi targets successfully recognized as you can see below
![screen shot 2018-01-08 at 10 51 15](https://user-images.githubusercontent.com/23318355/34665798-e924b7b4-f461-11e7-8a95-83de1501649a.png)

Once I try to start the filesystem it fails on step 2/5 saying that the "Journal size too big for filesystem"

I manually did it with success before using IML, thus I don't know:
- why it fails now
- why it tries to format it in ldiskfs instead of zfs: I tried with `create_installer zfs`before running ```install``` for IML, but that didn't solve the problem
Shall someone help me?
I am running IML 4.0.2.0 on CentOS 7.4. MDS, MGS and OSS are CentOS 7.4 as well.

Here is the log file:
```
modprobe osd_ldiskfs: 0


mkfs.lustre --mdt --mgsnode=192.168.50.186@tcp0 --mgsnode=192.168.50.187@tcp0 --failnode=192.168.50.188@tcp0 --reformat --index=0 --mkfsoptions=-I 512 -i 2048 -J size=2048 --backfstype=ldiskfs --fsname=vol1-tst /dev/disk/by-id/scsi-3600140586a303d4d1584fb290c8f3968: 1

   Permanent disk data:
Target:     vol1-tst:MDT0000
Index:      0
Lustre FS:  vol1-tst
Mount type: ldiskfs
Flags:      0x61
              (MDT first_time update )
Persistent mount opts: user_xattr,errors=remount-ro
Parameters:  mgsnode=192.168.50.186@tcp:192.168.50.187@tcp failover.node=192.168.50.188@tcp

device size = 1024MB
formatting backing filesystem ldiskfs on /dev/disk/by-id/scsi-3600140586a303d4d1584fb290c8f3968
  target name   vol1-tst:MDT0000
  4k blocks     262144
  options       -I 512 -i 2048 -J size=2048 -q -O dirdata,uninit_bg,^extents,mmp,dir_nlink,quota,huge_file,flex_bg -E lazy_journal_init -F
mkfs_cmd = mke2fs -j -b 4096 -L vol1-tst:MDT0000 -I 512 -i 2048 -J size=2048 -q -O dirdata,uninit_bg,^extents,mmp,dir_nlink,quota,huge_file,flex_bg -E lazy_journal_init -F /dev/disk/by-id/scsi-3600140586a303d4d1584fb290c8f3968 262144
   
   Journal size too big for filesystem.


mkfs.lustre FATAL: Unable to build fs /dev/disk/by-id/scsi-3600140586a303d4d1584fb290c8f3968 (256)

mkfs.lustre FATAL: mkfs failed 256
```
Thanks in advance.

**Comment by Libeccio84** [comment]
I found how to change the journal size via the "JOURNAL_SIZE" parameter in chroma/settings.py, but I still cannot create a lustre FS over zfs...

**Comment by jgrund** [comment]
Hi @Libeccio84,

Are you attempting to create a ZFS only fs?

Can you attach iml-diagnostics so we can investigate further?

**Comment by Libeccio84** [comment]
Unfortunately I cannot create it, thus I cannot attach any diagnostic report. What I would like to do is to create a lustre volume with the option `--backfstype=zfs`.
I can do that manually, But I would like to have it done via IML. Is there a parameter I have to set in order to have volumes with zfs backfs instead of ldiskfs?

**Comment by jgrund** [comment]
Hi @Libeccio84 ,

Even though the fs hasn't started, the `iml-diagnostics` command will still work on the manager and storage nodes.

IML doesn't currently support creating zpools from disks automatically (we've been considering that on our roadmap). 

For now, you will need to create the pools manually and export them. Once you do, IML will recognize them and you can select them for inclusion in a ZFS filesystem.

I would suggest starting from a clean slate, create all the pools, and proceed from there.

You can reference this doc for an example of how we setup a managed ZFS filesystem on our development nodes (the specifics are different, but general idea is the same): https://intel-hpdd.github.io/Online-Help/docs/Contributor_Docs/cd_Managed_ZFS.html.

**Comment by Libeccio84** [comment]
Ok, I will, but I thought IML was able to do this by itself.
I hope that this functionality might be taken into account as a feature request.
So far, thanks again for the support :)
