### ISSUE TITLE
Steps needed to build outside of the internal Intel network

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#45]
The steps we need to take to get fully open and building outside of the internal Intel network:

- [x] curl https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/npm/-/npm-3.10.6.tgz > /tmp/npm-3.10.6.tgz
- [x] Remove all references to artifactory.

**Comment by jgrund** [comment]
We shouldn't need to curl this anymore. This was only done to accommodate building without touching external networks.

**Comment by jgrund** [comment]
Node itself comes with npm in tow. That means, once we pull node, we should have npm.

**Comment by jgrund** [comment]
In other words, we should be able to just remove that line.
