### ISSUE TITLE
Replace usage of block_devices.normalized_device_table in lustre.py

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#460]
when removing deprecated code due to changes as part of #440 it became apparent that 

https://github.com/intel-hpdd/intel-manager-for-lustre/blob/11d1f5d6215bb553e2c3d458405dabe0b7874406/chroma-agent/chroma_agent/device_plugins/linux_components/block_devices.py#L15

cannot be removed despite of it longer being referenced from 

https://github.com/intel-hpdd/intel-manager-for-lustre/blob/11d1f5d6215bb553e2c3d458405dabe0b7874406/chroma-agent/chroma_agent/device_plugins/linux.py#L1-L105

because it is still being referenced inside  

https://github.com/intel-hpdd/intel-manager-for-lustre/blob/11d1f5d6215bb553e2c3d458405dabe0b7874406/chroma-agent/chroma_agent/device_plugins/lustre.py#L20

in order to get access to a populated normalized device table (ndt).

The relevant information required in lustre should be provided by the `device-aggregator` in some other way and then the `block_devices.py` file can be removed from the agent.

**Comment by jgrund** [comment]
It's also referenced in: https://github.com/intel-hpdd/intel-manager-for-lustre/blob/18f001a08e0b1e3027e38d3bd77d3bce777d9762/chroma-agent/chroma_agent/action_plugins/detect_scan.py#L52-L53

**Comment by jgrund** [comment]
De-scoping from 4.1
