### ISSUE TITLE
Pools need to be imported before creating filesystem in SSI tests

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#484]
During SSI runs on #467  zpool volumes are not reported when not imported on any hosts, hence when starting a filesystem during tests, after the created zpools  have been exported from all hosts during test setup, tests fail because the volumes are not reported on all hosts.

This could be solved by simply keeping the pool imported on a single host after it's creation.

**Comment by jgrund** [comment]
> This could be solved by simply keeping the pool imported on a single host after it's creation.

That's the right way to do this given we are only considering imported pools as usable going forward.

**Comment by tanabarr** [comment]
fix integrated into #467
