### ISSUE TITLE
No device found for name MGS: Invalid argument

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#485]
### Description 

test_writeconf_conf_params fails with:

```
test_writeconf_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 83, in test_writeconf_conf_params
    self.set_state(fs['mgt']['resource_uri'], 'mounted')
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 503, in set_state
    msg)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 487, in set_value
    command = self.wait_for_command(self.chroma_manager, command_id, verify_successful=(verify_successful != self.VERIFY_SUCCESS_NO), msg=msg, timeout=LONG_TEST_TIMEOUT)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 344, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/54/', u'/api/job/55/'], u'complete': True, u'created_at': u'2018-02-26T22:22:26.306076', u'message': u'Start target MGS', u'cancelled': False, u'errored': True, u'resource_uri': u'/api/command/13/', u'id': 13, u'logs': u'\n'}
```

### Repro

Run SSI->test_writeconf_conf_params with current [b2_10](https://build.hpdd.intel.com/job/lustre-reviews/54732/)

This is actually a follow-on effect from [LU-10760](https://jira.hpdd.intel.com/browse/LU-10760) in which the MGS startup can actually take 10-11 seconds **after** the `mount` command for it has returned.

This is a change in behaviour for Lustre.  Prior to the [current b2_10](https://build.hpdd.intel.com/job/lustre-reviews/54732/) there were at most a small number of seconds between the `mount` returning and the MGS being up, if any.

**Comment by jgrund** [comment]
Is this a failure due to the above Lustre change, or is it occurring even after waiting for the the async mount to occur?

**Comment by brianjmurrell** [comment]
> Is this a failure due to the above Lustre change

The referenced review (the [b2_10](https://build.hpdd.intel.com/job/lustre-reviews/54732/) above) is just b2_10 plus a [patch](https://jira.hpdd.intel.com/browse/LU-10676) we need to fix a packaging bug.  There is an open question in [LU-10676](https://jira.hpdd.intel.com/browse/LU-10676) about where RHEL 7.5 support will be released from to see how we get that fix in something more official than a review build.

> is it occurring even after waiting for the the async mount to occur?

If you mean waiting for the target start to complete (as opposed to the `mount` completing and returning) , we don't yet have code to do that.  I was waiting to see how the Lustre team responds to [LU-10676](https://jira.hpdd.intel.com/browse/LU-10676) before venturing into writing that code.  But if you think it's important enough to know beforehand, I can write that up and push a test.

**Comment by brianjmurrell** [comment]
The source of this has been tracked down and #426 will resolve it.
