### ISSUE TITLE
Use zfs properties provided through device-aggregator

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#498]
The manager and agent still access zfs device properties on the storage servers through CLI calls and this will be remedied in https://github.com/intel-hpdd/iml-common/issues/36 . The calls from agent and manager code need to be replaced with usages of properties stored somehow from the output of the `device-aggregator`  .

**Comment by jgrund** [comment]
I think I can make this easier by including the zfs props inline with the pools / datasets.

I can probably simplify this for you by inlining the entire tree structure.
