### ISSUE TITLE
Fix logfile time stamps

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#50]
Job scheduler log time stamps are in UTC time zone whereas chroma agent log time stamps are in PDT (presumably local time zone). Ensure all logs have the same time zones.

**Comment by tanabarr** [comment]
https://jira.hpdd.intel.com/browse/HYD-5008 duplicate

**Comment by jgrund** [comment]
This may be easier now if we simply write all agent logs to the journal.
