### ISSUE TITLE
clear_device_commands() not properly clearing devices

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#500]
We get test runs that hang up on LVM commands due to waiting for input from the user.

This shouldn't happen as https://github.com/intel-hpdd/intel-manager-for-lustre/blob/27c0e47d1d04434fe78fe81c1531dd071a88d876/chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py#L43-L57 is supposed to be clearing devices sufficiently that LVM won't prompt.

**Comment by jgrund** [comment]
This should be fixed by: https://github.com/intel-hpdd/device-scanner/pull/162

**Comment by brianjmurrell** [comment]
If intel-hpdd/device-scanner#162 does fix it there is a [patch](https://github.com/intel-hpdd/intel-manager-for-lustre/commit/36a6a37c9e9819ec6dbb5bd6f2d1e4851f72a399) to be reverted.

**Comment by jgrund** [comment]
Thanks! 

PR for revert [here](https://github.com/intel-hpdd/intel-manager-for-lustre/pull/595)
