### ISSUE TITLE
Manual Testing - 4.0.4.0

### ISSUE THREAD

**Issue by johnsonw** [intel-hpdd/intel-manager-for-lustre#503]
**Monitored ZFS**
Detecting Filesystem:
The first time I attempted to detect the filesystem it failed:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1100657/37548206-ab3a97c8-294c-11e8-88fc-cefb3e27c40a.png">

```
Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 316, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 537, in run
    AgentDaemonRpcInterface().update_host_resources(host.id, plugin_data)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 555, in <lambda>
    return lambda *args, **kwargs: self._call(name, *args, **kwargs)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 582, in _call
    raise RpcError(result['exception'], result.get('exception_type'), traceback=result.get('traceback'))
RpcError: RpcError: u'8:33'
```

It's possible that I needed to wait a little bit longer before attempting to detect the filesystem. I attempted to detect the filesystem a second time about 5 minutes later and it was successful:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/1100657/37548182-8a46b114-294c-11e8-98c8-44a940661beb.png">

Filesystem:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1100657/37548264-f279c208-294c-11e8-9107-de3e858bc2a6.png">

After connecting the client:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1100657/37548490-aeaaa89c-294e-11e8-8cd0-c8fec5c05264.png">

**Comment by johnsonw** [comment]
[sosreport-adm.lfs.local-20180316192821.tar.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1821033/sosreport-adm.lfs.local-20180316192821.tar.zip)

**Comment by johnsonw** [comment]
iml-diagnostics for monitored zfs test:
[sosreport-adm.lfs.local-20180316193720.tar.xz.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1821043/sosreport-adm.lfs.local-20180316193720.tar.xz.zip)

**Comment by jgrund** [comment]
Full traceback:

```
[2018-03-16 22:48:37,456: ERROR/rpc] ServiceRpcInterface._call: exception u'8:33': KeyError 	traceback: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 124, in run
    'result': self.rpc._local_call(self.body['method'], *self.body['args'], **self.body['kwargs']),

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 606, in _local_call
    return fn(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 27, in update_host_resources
    self.handlers[plugin_name].update_host_resources(host_id, data)

  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 224, in inner
    return func(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 98, in update_host_resources
    session.plugin.do_agent_session_continue(data)

  File "/usr/share/chroma-manager/chroma_core/lib/storage_plugin/base_plugin.py", line 135, in do_agent_session_continue
    self._update(self.agent_session_continue, self._root_resource.host_id, data)

  File "/usr/share/chroma-manager/chroma_core/lib/storage_plugin/base_plugin.py", line 212, in _update
    fn(*args)

  File "/usr/share/chroma-manager/chroma_core/plugins/linux.py", line 184, in agent_session_continue
    self.agent_session_start(host_id, data, initial_scan=False)

  File "/usr/share/chroma-manager/chroma_core/plugins/linux.py", line 385, in agent_session_start
    initiate_device_poll = self._map_drives_to_device_to_node(devices, host_id, 'zfsdatasets', ZfsDataset, ['name'], reported_device_node_paths) or initiate_device_poll

  File "/usr/share/chroma-manager/chroma_core/plugins/linux.py", line 464, in _map_drives_to_device_to_node
    drive_res = self.major_minor_to_node_resource[drive_bd]

KeyError: u'8:33'

[2018-03-16 22:48:37,470: ERROR/job_scheduler] Job 54 step 0 encountered an error: RpcError: u'8:33':Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 316, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 537, in run
    AgentDaemonRpcInterface().update_host_resources(host.id, plugin_data)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 555, in <lambda>
    return lambda *args, **kwargs: self._call(name, *args, **kwargs)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 582, in _call
    raise RpcError(result['exception'], result.get('exception_type'), traceback=result.get('traceback'))
RpcError: RpcError: u'8:33'
```

**Comment by jgrund** [comment]
As another data-point, just tried a monitored mode deploy locally and didn't see this.

**Comment by johnsonw** [comment]
**Managed Mode Test**
Creating Filesystem:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1100657/37554912-d73d9e1a-29b5-11e8-9db2-14fc24fb84c3.png">

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1100657/37554916-e2b98df8-29b5-11e8-84a6-70d723296e10.png">

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1100657/37554918-eb838e98-29b5-11e8-8a41-c5bcb4e2a859.png">

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/1100657/37554920-fa514ffa-29b5-11e8-86a2-1b3dd6597e77.png">

Connecting a Client:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/1100657/37554951-62c683a2-29b6-11e8-95b8-e83e0c5c1cfa.png">

Chart Data:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/1100657/37554954-6fbabd6c-29b6-11e8-8685-ee2412f28323.png">

After halting OSS1:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/1100657/37554994-fdb85dae-29b6-11e8-81ea-8f51dda8c8d3.png">

**Comment by jgrund** [comment]
As another data-point, tried the same managed scenario and saw the MDS / MGS targets setup on both filesystems. 

![screen shot 2018-03-17 at 11 45 50-fullpage](https://user-images.githubusercontent.com/458717/37557298-d26bc808-29d8-11e8-8480-350f055a2896.png)


Do you see any failed commands or traces in the manager / agent logs? Going forward we should collect and post iml-diagnostics for any unexpected issues.

**Comment by johnsonw** [comment]
I'm attempting to re-install managed mode a second time to see if I can reproduce the non HA MDS's. After installing the four servers, here is what the volumes page looks like:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/1100657/37557916-1c6fde72-29e2-11e8-9765-46f25e46fc64.png">

And the tree view:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/1100657/37557939-6b3794fa-29e2-11e8-9c33-fbec6fb6dc04.png">

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1100657/37557944-7776eac2-29e2-11e8-8eff-75abcdb874f7.png">

**Comment by johnsonw** [comment]
Just an update that after re-doing the Managed mode test the MDS's were created with HA pairs:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/1100657/37558062-978a181e-29e4-11e8-8e62-72c2ee165488.png">

**Comment by johnsonw** [comment]
**Managed ZFS Mode Test:**
While installing the servers one of my servers failed to configure corosync and ntp:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1100657/37607793-5b693086-2b6f-11e8-916b-ede6b2ca2013.png">

Attached sos report for MDS1:
[sosreport-mds1.lfs.local-20180319121703.tar.xz.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1825886/sosreport-mds1.lfs.local-20180319121703.tar.xz.zip)

Note that I don't believe this is an issue at this point. It's probably a hiccup in my local installation as I had an intermittent connectivity issue during the install. I'm going to re-install this box and read through the sos report to determine the reason.

**Comment by johnsonw** [comment]
Manual testing looks good. I have tested the following:
1. Monitored ZFS Mode
2. Managed Mode
3. Managed ZFS Mode 
   - Additionally tested that the target could not be mounted upon starting the filesystem. Fixed the mount issue and attempted failback. The test was successful.

I believe we have done our due diligence and was able to get through all scenarios listed above.
