### ISSUE TITLE
update installer for CentOS 7.5

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#550]
When we know what the actual version of CentOS 7.5 will be, we need to update the installer to accept it's version.

**Comment by jgrund** [comment]
Dup of #603

**Comment by brianjmurrell** [comment]
Well, not really a dup.  #603 was the PR for this issue and closing #603 would have closed this with a "Fixes ...".

I had actually intended to push the patch onto the issue, converting it to a PR but I frequently forget about doing that.
