### ISSUE TITLE
Disable actions button in monitored mode

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#559]
When no action is available for a given target, such as when in monitored mode, we should grey out the button or remove it, this should be as simple as enumerating through available actions for a target and disabling the button if there are none.

**Comment by jgrund** [comment]
@tanabarr screen-grab? This should be addressed in most places already.

**Comment by jgrund** [comment]
We do have this behavior on rewritten screens, this will fall out once we the fs detail screen has been updated.
