### ISSUE TITLE
IML4.0.5 and MGS failed to start after reboot

### ISSUE THREAD

**Issue by chowo12345** [intel-hpdd/intel-manager-for-lustre#567]
### Description 
The partner completed the installation of Lustre with IML.  File system was also successfully built.  Various benchmarks have been conducted as well.  Everything is ok until the IT operator rebooted all systems as part of the preparation to launch this storage service to end-users  (Note: IT operator stopped the lustre file system first gracefully and then shut down/power cycle the servers).

Then all the server had also booted up, OS looks good. Then the issues pop up with the IML/Lustre services. 

Here are the symptoms for the IML failed to start up the lustre file system.

1. The file system cannot be started up using the 'start' button on the file system tab
2. Upon loading the file system page. We suggested MGS and MDT shall be started first in sequence. MGS is still not starting up but the MDT is online
3. OST cannot all start up and warn the message - The action will lead to the action : will turn OST-00000A (for example) offline

### Version
- HPE D6020 with two DL380 server as a set of OSS in intel standard OSS pair (4 OSS servers in total)
- MSA2050 with two DL380 for MDS pair (2 MDS servers in total)
- Infiniband driver , o2ib enabled
- CentOS 7.4
- Mellanox driver 4.3.1 with Intel Manager of Lustre 4.0.5

### iml-diagnostics
SOS Report generated from iml-diagnostics can be downloaded from the following link:
[https://drive.google.com/uc?export=download&confirm=X0A2&id=1Dia6Siz6oOq4gXX1MhCTNjkGLxK8bqV5](https://drive.google.com/uc?export=download&confirm=X0A2&id=1Dia6Siz6oOq4gXX1MhCTNjkGLxK8bqV5)
There are a few screen captures of the error.  Not sure whether this will help.

**Comment by chowo12345** [comment]
https://1drv.ms/u/s!AgjiaClb_wgkhzUzBNG__tUeBI4v 

Please try this link for SOS Report.

**Comment by chowo12345** [comment]
Just checked with the IT Operator .... he used this as reference https://github.com/intel-hpdd/intel-manager-for-lustre/issues/434  and change the starting sequence.  It seems ok now.  I am trying to gather more info. and share here ... :)

**Comment by brianjmurrell** [comment]
> Please try this link for SOS Report.

In the future, please attach SOS Reports directly to issues so that we don't have these problems of links dying.

Thanks.

**Comment by chowo12345** [comment]
@brianjmurrell  The SOS Report is 69MB in size and won't allow to attach directly ... Is there anything in the report can be eliminated?  So I can better prepare in the future ... :)

**Comment by brianjmurrell** [comment]
@chowo12345 Ahhh.  I see.  We have done some work to reduce the size of those most recently.  Hopefully that will help.

**Comment by jgrund** [comment]
Looks like you've managed to fix this one @chowo12345, closing. Please reopen if you'd like to discuss further.
