### ISSUE TITLE
Record format of Lustre Audits

### ISSUE THREAD

**Issue by johnsonw** [intel-hpdd/intel-manager-for-lustre#568]
As we evaluate the future of stats collection in IML, we should record what stats we currently collect today to ensure we don't lose any data collection.

**Comment by johnsonw** [comment]
This gist contains metric data for one of the oss' and includes jobstats: https://github.intel.com/gist/wcjohnso/efee5d772332f16fc7c433117dbf3172

**Comment by johnsonw** [comment]
LNet: https://github.intel.com/gist/wcjohnso/6bb89c6cd2f25533464312fb5bf04917

**Comment by johnsonw** [comment]
MGS: https://github.intel.com/gist/wcjohnso/21cf6272a076cd5992cda76792ad9512

**Comment by johnsonw** [comment]
MDT: https://github.intel.com/gist/wcjohnso/cebd8562f355a75178f335fb0b80d274

**Comment by jgrund** [comment]
Thanks @johnsonw
