### ISSUE TITLE
Create service grouping systemd units

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#572]
Now that we are creating smaller stand-alone services, we need the ability to start / stop them in tandem.

We can create either a `iml-storage-server.target` or dummy `iml-storage-server.service` unit to control starting / stopping these services in tandem.

This will handle the following services (so far) either directly or indirectly:

  - chroma-agent
  - device-scanner
  - scanner-proxy
  - mount-emitter

Things we need to consider:

1. We should repopulate the scanner if the service has stopped, but not if it has been running since boot.

**Comment by brianjmurrell** [comment]
> dummy iml-storage-server.service unit to control starting / stopping these services in tandem

Let's NOT do this.  There are other project(s) that do this and it's nasty.

_systemd_ seems sufficiently powerful enough that we should let it work things out for itself, if we can.

**Comment by jgrund** [comment]
> Let's NOT do this. There are other project(s) that do this and it's nasty.

I'm not sure the alternative is less nasty. What are you proposing here?

**Comment by brianjmurrell** [comment]
I'm proposing not burying the ordering and binding of units in another unit file which the user has to figure out and edit if/when their situation doesn't walk the happy-path.

**Comment by jgrund** [comment]
So, how does service ordering / binding work in your scenario? There will either have to be a single unit  that acts as the control unit, or things that need to start / stop services will need to list all of them explicitly.

**Comment by brianjmurrell** [comment]
_systemd_ seems to have some pretty powerful mechanisms for starting, stopping, ordering and binding services.  Are the existing mechanisms not sufficient?  If not, where is it lacking?

**Comment by jgrund** [comment]
Here are the requirements btw.

1. Stopping should stop *all* services / sockets / path units.
2. Starting should start *all* sockets / path units and any services that don't use socket / path activation.
3. Starting should optionally pre-populate the device-scanner if it isn't running at boot time.

1 & 2 are doable, I'm still unsure if 3 is easily doable.

**Comment by jgrund** [comment]
> systemd seems to have some pretty powerful mechanisms for starting, stopping, ordering and binding services. Are the existing mechanisms not sufficient? If not, where is it lacking?

The powerfulness of systemd is orthognal though, the question really is how does one stop / start all collaborating services on a storage server, i.e. what command(s) do they enter?

**Comment by brianjmurrell** [comment]
> what command(s) do they enter?

Ideally, `systemctl start $unit`.

I'm not sure I fully understand 4.  What exactly is the use-case and issue?

**Comment by brianjmurrell** [comment]
> proposing, that we have a single control unit that in turn is responsible for that.

Right, which I am agreeing with.  I just don't want to see it all done inside a "startup script" that handles starting/stopping the individual units vs. giving _systemd_ enough information to handle the starting/stopping/ordering/binding itself.

> device-scanner will start at boot when it gets uevents / zed events. It will start before the agent / other services so it can catch all those events at startup.

Right.

> The tricky bit is once the scanner is stopped it needs to be repopulated with that same data

Do you mean when the scanner is stopped and then started again, it needs to be populated with all of the data that it would have gotten running from boot?  I.e. being populated with the data from event 0 until present.

> conditionally execute those commands so they don't get run at boot time and only during service stop -> start / restart.

What happens if those commands are run when the scanner is started at boot?  Isn't it effectively a NOOP since it is starting at event 0 already?  Or is there some reason this NOOP activity can't be run at boot?

**Comment by jgrund** [comment]
> Right, which I am agreeing with. I just don't want to see it all done inside a "startup script" that handles starting/stopping the individual units vs. giving systemd enough information to handle the starting/stopping/ordering/binding itself.

Indeed, I think we are on the same page then. I am proposing a single unit that uses systemd directives to organize the sub-units, no imperative scripting.

> Do you mean when the scanner is stopped and then started again, it needs to be populated with all of the data that it would have gotten running from boot? I.e. being populated with the data from event 0 until present.

yes

> What happens if those commands are run when the scanner is started at boot? Isn't it effectively a NOOP since it is starting at event 0 already? Or is there some reason this NOOP activity can't be run at boot?

I'm not sure it would be a noop as there would be events incoming from udev / zed. More than likely it would cause some undesired interleaving, or cancel out some rules perhaps as I'm using a trigger change over the block subsystem.
