### ISSUE TITLE
reactive stack causing test job hang

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#579]
### Description 

There is a stuck test job (5 days stuck now) on lotus-44:1 at:

```
2018-05-03 08:12:18,970 - test - DEBUG -         self.wait_until_true(lambda: self.targets_in_state('unmounted'))
 evaluated to False
```

This test job is a result of testing on the [reactive stack PR](#467) so it's probably a good idea to understand the nature of the hung job to see if it's still a current issue in that stack.

**Comment by jgrund** [comment]
I'll take a look

**Comment by jgrund** [comment]
They are being purposely paused.

If you look at bash history on the test node, you can see: ` kill -STOP 17106`

Where:

```
root     17106  0.0  1.6 480368 31296 ?        T    May08   0:12 /usr/bin/python /usr/bin/nosetests -x --verbosity=2 --exclude=.*test_cluster_setup.* --tc-format=json --tc-file=/root/cluster_cfg.json --with-xunit --xunit-file=/root/test_report_zfs_HA_is_false.xml tests/integration/existing_filesystem_configuration/
```

Agree the jobs should be aborted afterwards.
