### ISSUE TITLE
Volumes Configuration ||  Fail-over  Server  || 400(error)

### ISSUE THREAD

**Issue by atulyadavtech** [intel-hpdd/intel-manager-for-lustre#581]
### Description 

Volumes Failover server configution not working 
Getting 400(error)

### Repro

What steps were taken leading to this issue
Enable the Volumes Failover configuration.

### Version

What version of IML? iml-4.0.5.0.tar.gz
What Operating System? CentOS Linux release 7.4.1708 (Core)
What Operating System version?

### iml-diagnostics

Attach any [`iml-diagnostics`](htt

ps://intel-hpdd.github.io/Online-Help/docs/Errors_Troubleshooting_12_0.html#12.2) for nodes relevant to this issue.
![image](https://user-images.githubusercontent.com/13992953/39772515-1bd7e90a-5313-11e8-817f-0b67c63b631a.png)

**Comment by johnsonw** [comment]
Hi @atulyadavtech,

Can you please:
1. upload a couple of screenshots showing the volumes page and the steps that were taken when the problem occurred?
2. run iml-diagnostics on the manager node and attach to this ticket

Just to confirm, you're able to reproduce this by selecting the failover target on the volumes page and then attempting to save the changes, correct?

Regards,

Will
