### ISSUE TITLE
ZFS Drive Drop Caused Lustre Failure

### ISSUE THREAD

**Issue by UnknownNet** [intel-hpdd/intel-manager-for-lustre#584]
### Description 

We have an IML managed Lustre filesystem using ZFS on attached JBODS. ZFS reported a drive failure, multipath marked the path down, and PCS/IML started a boot loop as the OST resources bounced from partner to partner. Ultimately, it was found that lock files in /var/lib/iml/zfs_lock were not cleaning up correctly and allowing the resources to come online.

What creates those lock files and what cleans them up? Also, we have systems currently running where those lock files are not there, should they be?

### Repro

At this point, we've been unable to reproduce. Understanding the zfs_lock directory will help in chasing this issue down loater.

### Version

What version of IML? 4.0.4.0
What Operating System? CentOS
What Operating System version? 7

**Comment by jgrund** [comment]
Given this is going away in the soon to be released 4.1, I will close this.
