### ISSUE TITLE
Enhance EFS & SSI tests to simulate mixed device type environments

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#600]
Tests should be improved to operate over mixed device type installations:

* Remove hardcoded device type operations, use methods in abstracted device type specific subclasses (for example there are various `zpool` commands issued in integration tests)
* Install and remove packages per test run based on which host is required to handle targets of specific device type

**Comment by brianjmurrell** [comment]
> Install and remove packages per test run based on which host is required to handle targets of specific device type

This is already handled by profile selection for the host in a test run.

**Comment by brianjmurrell** [comment]
> Remove hardcoded device type operations, use methods in abstracted device type specific subclasses (for example there are various zpool commands issued in integration tests)

An example of this is: https://github.com/intel-hpdd/intel-manager-for-lustre/blob/742f2db644b3e5b2e8fa4d0203fcaa3d420b5bb7/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py#L170-L172 where `zpool import` is being run on `host_addresses[0]` (which is `self.TEST_SERVERS[0]`) without regard to whether that host has ZFS targets and therefor has ZFS even installed.

A short-term hack to fix this could look like:

```patch
diff --git a/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py b/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
index 4d54ed3c7..645ccd413 100644
--- a/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
+++ b/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
@@ -167,7 +167,7 @@ class TestManagedFilesystemWithFailover(FailoverTestCaseMixin, StatsTestCaseMixi
         hosts = self.add_hosts(host_addresses)
         self.configure_power_control(host_addresses)
 
-        self.execute_commands(['zpool import -a'],
+        self.execute_commands(['which zpool && zpool import -a'],
                               host_addresses[0],
                               'import all pools')
 
```

but I think the right way to deal with this is to use what we know about the `config`uration to guard the `execute_commands()` from even running if we know that `self.TEST_SERVERS[0]` doesn't have ZFS installed.

**Comment by jgrund** [comment]
>  use methods in abstracted device type specific subclasses

I think this is actually an issue to proceed forward in this way. Using device specific subclasses boxes us in more than necessary, and is the current cause of some pain in production code.

IMO, a better approach is to avoid subclassing altogether, rely more heavily on the passed in config  being the datasource, and use modules (functions) as the unit of organization, not a class hiearchy.
