### ISSUE TITLE
installation on plain RedHat 7.4 fails for IML latest release

### ISSUE THREAD

**Issue by kbuggenhout** [intel-hpdd/intel-manager-for-lustre#650]
### Description 

when trying to install IML 4.0.6 ( latest release, installing a managed storage node fails because of unresolved dependencies in dnf. 
first dependency issue at agent deployment : rpm-plugin-systemd-inhibit not found
second issue at deploying managed storage server : fence-agents-virsh not found

fixed for now by adding CentOS 7.4 repo's to the yum,repos.d, which is a bit of a sledgehammer approach to fixing it.

### Repro

install a node with RedHat 7.4, disable selinux ( had to do that to move the postgres db to a larger disk), disable firewall, install IML from tarball, setup a second node as storage server, RH7.4, disable selinux, disable firewall, install the node through IML : fails

### Version

What version of IML 4.0.6
What Operating System? RedHat
What Operating System version? 7.4

### iml-diagnostics

---> Package librepo.x86_64 0:1.7.16-1.el7 will be installed
---> Package libsolv.x86_64 0:0.6.26-2.el7 will be installed
---> Package python2-dnf.noarch 0:1.1.5-2.01.el7.centos will be installed
--> Processing Dependency: rpm-plugin-systemd-inhibit for package: python2-dnf-1.1.5-2.01.el7.centos.noarch
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
" stderr: "https://iml.hpc.local:443/repo//iml-agent/7Server/repodata/repomd.xml: [Errno 14] curl#51 - "Unable to communicate securely with peer: requested domain name does not match the server's certificate."
Trying other mirror.
Error: Package: python2-dnf-1.1.5-2.01.el7.centos.noarch (managerforlustre-manager-for-lustre)
           Requires: rpm-plugin-systemd-inhibit
"
[2018-06-12 03:11:04,122] bootstrap bootstrap INFO Agent bootstrap started...
[2018-06-12 03:11:04,142] bootstrap bootstrap INFO Executing shell command with arguments: ['openssl', 'genrsa', '-out', '/var/lib/chroma/private.pem', '2048']
[2018-06-12 03:11:04,222] bootstrap bootstrap DEBUG Command returned 0: stdout: "" stderr: "Generating RSA private key, 2048 bit long modulus

**Comment by brianjmurrell** [comment]
Hi.

_rpm-plugin-systemd-inhibit_ is in the RHEL _optional_ channel.

Please refer to the [Server Configuration section](https://intel-hpdd.github.io/Online-Help/docs/Install_Guide/ig_ch_04_pre_install.html#server-configuration) of the [Pre-installation Tasks documentation](https://intel-hpdd.github.io/Online-Help/docs/Install_Guide/ig_ch_04_pre_install.html).

**Comment by kbuggenhout** [comment]
Thnx brian, missed that litle nugget :)

did all my test deploys on a CentOs based system, this is the first one on e 'RH' one

**Comment by brianjmurrell** [comment]
I'm going to close this ticket, but please do let us know if you need any more help in this regard and feel free to open any tickets for any other issues you run into.

**Comment by kbuggenhout** [comment]
just a small one, did a quick test and now it fails on the fence-agents-virsh, but I guess thats because the RedHat version is 7.4 not 7.5

**Comment by kbuggenhout** [comment]
will drop down to the IML rev that is ok with RH7.4 :)

**Comment by brianjmurrell** [comment]
_fence-agents-virsh_ is also in the _optional_ channel in RHEL 7.4.

**Comment by kbuggenhout** [comment]
I enabled the optional channel and it still fails, it didnt stumble on the rpm-plugin-systemd-inhibit, but it dies at dnf no fence-agents available ( when digging in the dnf logs, its fence-agents-virsh)

**Comment by kbuggenhout** [comment]
if I add the CentOS repo's as backup, and make sure that works, the installation goes smooth

**Comment by brianjmurrell** [comment]
> I enabled the optional channel and it still fails, it didnt stumble on the rpm-plugin-systemd-inhibit, but it dies at dnf no fence-agents available ( when digging in the dnf logs, its fence-agents-virsh)

With the optional channel enabled, does `yum install fence-agents` fail?  If so, can you paste the output here?

> if I add the CentOS repo's as backup, and make sure that works, the installation goes smooth

While I most certainly cannot speak for RedHat, I would suspect that such a configuration would be outside of their parameters for a supported system and having a supported system is afterall the entire point of using RHEL, otherwise of course you could just use CentOS.

**Comment by brianjmurrell** [comment]
That's all fair enough.

However, without the previously requested `yum` output there is not much else I can suggest other than opening a case with RedHat about the inability to find the packages that should be in that enabled _optional_ channel.
